"""Tests for the client-communications output generators."""

from __future__ import annotations

import pytest

from satc.intake.outputs import (
    escape_html,
    format_output_date,
    generate_client_request_email,
    generate_client_request_print_html,
    generate_internal_checklist_print_html,
    group_tasks_by_category,
)
from satc.intake.workflows import build_engagement, load_workflow


@pytest.fixture()
def engagement():
    wf = load_workflow("personal_1040_core")
    return build_engagement(
        wf,
        client_id="SATC-001000",
        due_date="2026-04-15",
        answers={"newSatcClient": "yes", "marketplaceInsurance": "yes"},
        tax_year=2025,
    )


def test_email_contains_client_request_text_and_is_grouped(engagement):
    email = generate_client_request_email(engagement, client_name="Jordan Rivera")

    # Subject + greeting use the client name and workflow display name.
    assert "Subject: Requested items for Jordan Rivera - Personal 1040 core" in email
    assert "Hello Jordan Rivera," in email
    assert "Personal 1040 core" in email
    assert "due Apr 15, 2026" in email

    # Client request text for included tasks appears verbatim (whitespace-folded).
    assert "Upload Form 1095-A for Marketplace coverage." in email
    assert "Upload Forms W-2, 1099-INT" in email

    # Grouped by category: the category headings are present as standalone lines.
    lines = email.splitlines()
    assert "Core documents" in lines
    assert "Credits" in lines
    assert "Prior year" in lines

    # The category heading precedes its task line.
    credits_idx = lines.index("Credits")
    assert lines[credits_idx + 1].startswith("- Upload Form 1095-A")


def test_email_excludes_internal_only_instructions(engagement):
    email = generate_client_request_email(engagement, client_name="Jordan Rivera")

    # Internal instruction strings from the workflow config must not leak.
    assert "Reconcile premium tax credit" not in email
    assert "Reconcile uploaded tax forms" not in email
    assert "Internal instructions" not in email


def test_internal_checklist_contains_risk_flag_and_internal_instruction(engagement):
    html = generate_internal_checklist_print_html(engagement, client_name="Jordan Rivera")

    # Risk flag generated by marketplaceInsurance=yes.
    assert "Marketplace Form 1095-A required" in html

    # An internal instruction from an included task.
    assert "Reconcile premium tax credit" in html

    # Intake answers section reflects the yes answers via question labels.
    assert "New SAT-C client?" in html
    assert "Yes" in html


def test_client_print_html_excludes_internal_instructions(engagement):
    html = generate_client_request_print_html(engagement, client_name="Jordan Rivera")
    assert "Upload Form 1095-A for Marketplace coverage." in html
    assert "Reconcile premium tax credit" not in html
    assert "Internal instructions" not in html


def test_escape_html_escapes_brackets_and_ampersands():
    assert escape_html("<b>") == "&lt;b&gt;"
    assert escape_html("a & b") == "a &amp; b"
    assert escape_html('"quote"') == "&quot;quote&quot;"
    assert escape_html("it's") == "it&#039;s"
    assert escape_html(None) == ""


def test_format_output_date():
    from datetime import date

    assert format_output_date(date(2026, 4, 15)) == "Apr 15, 2026"
    assert format_output_date(None) == ""


def test_group_tasks_by_category_preserves_first_seen_order(engagement):
    groups = group_tasks_by_category(engagement.tasks)
    categories = [category for category, _ in groups]
    # First-seen order: Core documents (always), then Prior year, then Credits.
    assert categories[0] == "Core documents"
    assert "Credits" in categories
    assert len(categories) == len(set(categories))
