"""The operating procedures, generated from the software that performs them.

THE FIRM ASKED FOR THESE: "i will eventually want operating procedures and
stuff so it's integral everything works and can be demonstrated."

They are GENERATED, and that is the whole point. Every step below is read out
of the code that would run it -- the CLI's own subparsers, `packaging.PACKS`,
`presend.gate`, `closeout.questions_for` -- so this document

  * cannot describe a command that does not exist,
  * cannot list a document a return type does not get,
  * cannot claim a check the gate does not perform,
  * and cannot go stale, because `procedures --check` regenerates it and fails
    when the committed copy differs.

The same shape as `website/pricing.spec.py`, and for the same reason: a
procedure written by hand beside software is a procedure that is wrong within
a month, and nobody finds out until somebody follows it.

WHAT IS NOT GENERATED is the judgement -- when to decline work, whether a
divergence means the return changed or the interview was wrong. That belongs
to a person, and the places it does are marked rather than filled in.
"""

from __future__ import annotations

import inspect
import re
from pathlib import Path

import closeout
import packaging
import presend

ROOT = Path(__file__).resolve().parent
OUT = ROOT.parent / "docs" / "OPERATING-PROCEDURES.md"

# The four kinds of engagement, in the order a practice meets them.
RETURN_TYPES = [
    ("individual", "An individual", "1040"),
    ("partnership", "A partnership", "1065"),
    ("s_corp", "An S corporation", "1120S"),
    ("c_corp", "A C corporation", "1120"),
]


def commands() -> list[str]:
    """Every subcommand the CLI actually offers, read from its own parser.

    Read from source rather than by building the parser, because building it
    imports the world; the point is only that this list cannot drift from the
    commands that exist.
    """
    import cli
    src = inspect.getsource(cli.main)
    return re.findall(r'add_parser\("([a-z-]+)"', src)


def _require(name: str) -> str:
    """Fail loudly if a procedure names a command that has been renamed."""
    if name not in commands():
        raise RuntimeError(
            f"the procedures name `{name}`, which the CLI no longer offers. "
            f"Either the command was renamed or the procedure is wrong; a "
            f"document that tells someone to run a command that does not "
            f"exist is worse than no document.")
    return name


def gate_checks() -> list[str]:
    """What the pre-send gate verifies, from the gate itself."""
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        # An empty directory: nothing to find, so nothing fails, and what comes
        # back is the list of checks rather than a list of findings.
        result = presend.gate(Path(tmp), {}, rendered=None, skip_render=False)

    # The names are the gate's own, verbatim, so a check renamed in `presend`
    # is renamed here without anybody remembering to. (The gate used to append
    # a count to one of them -- "every document opens and renders (3)" -- and
    # this function stripped the bracket; the count now lives in the gate's
    # REPORT rather than in the check's name, so there is nothing to strip.)
    #
    # A skipped check is named as skipped rather than dropped: a procedure that
    # lists only what ran reads like a procedure where everything ran.
    return list(result.checked) + [
        f"{s} — only when the caller supplies the rendered text"
        for s in result.skipped]


def advisory_checks() -> list[str]:
    """What `--notes` reads, from the advisory register itself.

    Listed separately and said to be advisory, because the difference is the
    whole design: these ten never stop a pack. A procedure that ran them
    together with the blocking eight would teach a preparer that a note is a
    failure, and the next thing that happens is that the eight get ignored too.
    """
    import notes as _notes
    return [f"{a.key} ({a.tenet}) — {a.what}" for a in _notes.ADVISORIES]


def render() -> str:
    """The document."""
    lines: list[str] = []
    add = lines.append

    add("# SATC — operating procedures")
    add("")
    add("> **GENERATED. Do not edit this file.**")
    add(">")
    add("> Every step below is read out of the code that performs it — the")
    add("> CLI's own subparsers, `packaging.PACKS`, `presend.gate`,")
    add("> `closeout.questions_for`. It cannot name a command that does not")
    add("> exist, list a document a return type does not get, or claim a check")
    add("> the gate does not perform.")
    add(">")
    add("> Regenerate with `cd client-documents && python cli.py procedures`.")
    add("> `python cli.py procedures --check` fails when the committed copy has")
    add("> drifted, and runs in the suite, so a procedure cannot quietly stop")
    add("> being true.")
    add("")
    add("A procedure written by hand beside software is wrong within a month,")
    add("and nobody finds out until somebody follows it.")
    add("")

    # ── 1 · taking on a client ────────────────────────────────────────────
    add("## 1 · Taking on a new client")
    add("")
    add("```")
    add(f"python cli.py {_require('from-lead')} --lead lead.json --out record.json")
    add(f"python cli.py {_require('interview')}")
    add("```")
    add("")
    add("The website lead is a **claim**, not a fact: every prefilled answer is")
    add("still asked. The interview decides whether to take the work, prices it,")
    add("and creates the engagement — all in `intake.finish`, which the web and")
    add("CLI front doors share, so neither can lose a gate the other keeps.")
    add("")
    add("It refuses in three ways, each of them deliberate:")
    add("")
    add("- **work the firm does not take** — the hard-no list in")
    add("  `firm-settings.yaml`, refused before anything is composed;")
    add("- **a decision that is not yes** — nothing is created;")
    add("- **an unfinished interview** — a required question left unanswered")
    add("  stops the engagement, because creating it anyway puts the hole in a")
    add("  document instead, where a client finds it.")
    add("")
    add("> **Judgement, not procedure:** whether to override a hard-no. The")
    add("> option exists and it is recorded on the outcome. Use it when the list")
    add("> is wrong, not because this one feels like an exception.")
    add("")

    # ── 2 · the opening pack ──────────────────────────────────────────────
    add("## 2 · Sending the opening pack")
    add("")
    add("```")
    add(f"python cli.py {_require('doctor')} --engagement <REF>")
    add(f"python cli.py {_require('package')} --engagement <REF> --out packs/<REF>")
    add("```")
    add("")
    add("`doctor` says what is missing before you try. `package` is **atomic**:")
    add("every document is rendered to a temporary directory first, and the")
    add("output folder is only touched once all of them have succeeded. A pack")
    add("with a hole in it is worse than no pack at all — somebody signs what")
    add("arrived and the rest turns up later saying something different.")
    add("")
    add("What each kind of engagement is sent:")
    add("")
    add("| Engagement | Documents in the opening pack |")
    add("|---|---|")
    for key, label, form in RETURN_TYPES:
        docs = packaging.documents_for({"_return_type": key})
        add(f"| {label} ({form}) | {', '.join(f'`{d}`' for d in docs)} |")
    add("")
    conditional = ", ".join(f"`{d}` when `{flag}`"
                            for d, flag in packaging.CONDITIONAL.items())
    add(f"And conditionally: {conditional}.")
    add("")

    # ── 3 · the gate ──────────────────────────────────────────────────────
    add("## 3 · What the pre-send gate checks")
    add("")
    add("`package` runs these before it writes anything. Nothing has reached the")
    add("output directory yet, so a refusal costs nothing and leaves no half-pack")
    add("behind.")
    add("")
    for check in gate_checks():
        add(f"- {check}")
    add("")
    add("**Blocking, with a logged override.** A gate with no override will one")
    add("day stop a return going out at eleven at night and there will be nothing")
    add("to do about it; a gate that can be waved through silently is not a gate.")
    add("")
    add("```")
    add("python cli.py package --engagement <REF> --out packs/<REF> \\")
    add('    --force --reason "why this is going out as it is"')
    add("```")
    add("")
    add("`--force` needs `--reason`. What failed and why it was overridden are")
    add("appended to the engagement's own `overrides.json` — append-only, because")
    add("a log you can edit is not evidence. If the log cannot be written, the")
    add("pack is not written either.")
    add("")
    add("**Every check above reports how many things it examined.** A check with")
    add("nothing to look at prints `NONE`, never `ok`: on an opening pack there")
    add("is no cited clause to resolve, and for a while that printed as a pass.")
    add("")
    add("### The readings — `package --notes`")
    add("")
    add("Ten more checks that **never block and never change the exit code**.")
    add("They are the tenets a machine can only guess at, and each is promoted")
    add("to blocking only after a full cycle with no false positive.")
    add("")
    for check in advisory_checks():
        add(f"- {check}")
    add("")
    add("Run them on the round where somebody is reading the prose, not on every")
    add("send. An advisory printed beside a real failure every time is an")
    add("advisory people learn to scroll past — and they take the blocking")
    add("checks with them.")
    add("")
    add("Where a document promises something this software does not render —")
    add("an organizer, a payment voucher — declare it:")
    add("")
    add("```")
    add("python cli.py package --engagement <REF> --out packs/<REF> \\")
    for aid in sorted(packaging.ATTACHMENTS):
        add(f"    --attach {aid} \\")
    add("    # (only the ones actually going in the envelope)")
    add("```")
    add("")

    # ── 4 · the work changed ──────────────────────────────────────────────
    add("## 4 · When the work changes, and the price with it")
    add("")
    add("```")
    add(f"python cli.py {_require('requote')} --engagement <REF>")
    add(f"python cli.py {_require('requote')} --engagement <REF> \\")
    add("    --set count_rentals=2 --reason '<why, in one sentence>'")
    add("```")
    add("")
    add("A client rings in March: they bought a rental, a K-1 arrived, the")
    add("side business turned out to be a real one. **Nobody types a figure.**")
    add("The answers move and the same schedule that priced the engagement in")
    add("January prices it again — an amount typed onto an invoice by hand is")
    add("a second source for the same money, and the one the client keeps is")
    add("the one that says the larger number.")
    add("")
    add("Run with no `--set`, it lists the answers that move money — read out")
    add("of the fee schedule itself, and narrowed to the ones this client was")
    add("actually asked. In the browser it is **Update the quote** on the")
    add("engagement's own page.")
    add("")
    add("**Nothing is written without `--reason`.** The plan prints — every")
    add("line that moves, the new total, the difference — and the command")
    add("stops. A re-quote that could happen by accident is a price that moved")
    add("and cannot be explained a year later.")
    add("")
    add("Three things it refuses outright:")
    add("")
    add("- **answers that now flag work the firm does not take** — the")
    add("  engagement is already live, so what is needed is the disengagement")
    add("  letter, not a new price;")
    add("- **a re-quote that changes nothing** — a revision log full of no-ops")
    add("  is a log nobody reads, and a second estimate identical to the first")
    add("  confuses a client for no reason;")
    add("- **an incomplete interview** — it reprices the whole engagement, not")
    add("  one line, so it needs what the first price needed.")
    add("")
    add("What it writes: the amended answers, the repriced record, and one")
    add("entry in `revisions.json` beside the engagement — append-only, never")
    add("pruned, showing what was asked, what moved, and why. The same shape")
    add("as a waved-through gate failure, for the same reason.")
    add("")
    add("**Two dates, and only one of them moves.** The estimate gets today's;")
    add("the engagement letter keeps the date the client signed under. Two")
    add("sheets in a drawer showing different totals under the same date is a")
    add("question nobody can answer next February.")
    add("")
    add("> **Judgement, not procedure:** whether the pack goes out again. If")
    add("> the scope lines moved, the signed letter no longer describes the")
    add("> work and the re-quote says so — rebuild it. If only the figure")
    add("> moved, the letter still reads correctly and the estimate can go on")
    add("> its own.")
    add("")

    # ── 4 · billing ───────────────────────────────────────────────────────
    add("## 5 · Billing")
    add("")
    add("```")
    add(f"python cli.py {_require('invoice')} --engagement <REF> --billed '<period>'")
    add(f"python cli.py {_require('render')} --engagement <REF> --docs invoice --out out")
    add("```")
    add("")
    add("One engagement has many invoices, so each is written to its own file")
    add("rather than over the record. The invoice and the estimate must agree")
    add("about the reference and the figure and **must not** share `PeriodLabel`")
    add("— that is the one value naming two different spans of time.")
    add("")

    # ── 5 · closing ───────────────────────────────────────────────────────
    add("## 6 · Closing an engagement, at the end of the cycle")
    add("")
    add("```")
    add(f"python cli.py {_require('close')} --engagement <REF>")
    add("```")
    add("")
    add("Records what was **actually filed**, in-house. Nothing is read out of")
    add("Drake. The questions asked depend on the return:")
    add("")
    for key, label, form in RETURN_TYPES:
        asked = closeout.questions_for(key)
        add(f"**{label} ({form})** — {len(asked)} questions: "
            + ", ".join(f"`{q['id']}`" for q in asked))
        add("")
    add("An unanswered question is reported as unanswered, never as agreement.")
    add("")

    # ── 6 · the control ───────────────────────────────────────────────────
    add("## 7 · The end-of-cycle control")
    add("")
    add("```")
    add(f"python cli.py {_require('reconcile')}")
    add(f"python cli.py {_require('reconcile')} --apply")
    add("```")
    add("")
    add("Sweeps every engagement and reports where the filed return disagrees")
    add("with what the interview recorded months earlier. An engagement nobody")
    add("closed is reported as **NOT CLOSED**, never skipped: a control that only")
    add("examines the work somebody remembered to close is a control over the")
    add("diligent, which is not where the problem is.")
    add("")
    add("> **Judgement, not procedure:** a divergence is not an error. It is one")
    add("> of three things and only a person can tell which — the return changed")
    add("> after the interview, the interview was wrong, or the wrong thing was")
    add("> filed. `--apply` moves the record to match the return and writes every")
    add("> move to an append-only log. Next year's interview is seeded from those")
    add("> answers, which is why it matters that they are right.")
    add("")

    # ── 7 · next year ─────────────────────────────────────────────────────
    add("## 8 · The following year")
    add("")
    add("```")
    add(f"python cli.py {_require('returning')} --engagement <LAST YEAR'S REF>")
    add("```")
    add("")
    add("Last year's answers are shown back to be confirmed, never assumed —")
    add("every carried answer is still asked. Nine carry; the rest are asked")
    add("fresh, and the command prints why each one does not carry.")
    add("")
    add("A returning client is also asked what changed: a marriage, a divorce, a")
    add("birth, a death, a home bought or sold, a move, a retirement, an")
    add("inheritance. Those are recorded and flagged for you. What any of them")
    add("*means* for the return is a conversation with the client, and nothing")
    add("here turns a tick box into advice.")
    add("")

    # ── 8 · demonstrating it ──────────────────────────────────────────────
    add("## 9 · Demonstrating that all of it works")
    add("")
    add("```")
    add("cd client-documents && python exercise.py")
    add("```")
    add("")
    add("Runs every scenario end to end through the real commands, produces the")
    add("real documents, **opens each one in a browser** to confirm it rendered,")
    add("and cross-checks each pack against itself. Exits non-zero on a surprise.")
    add("")
    add("A `[CONFIRM: ]` in a registry is not a surprise. It is the software")
    add("saying a sentence a client will read has not been written yet, and")
    add("refusing rather than sending the placeholder; the harness reports those")
    add("as **waiting on the firm**.")
    add("")
    add("Every other command this document names:")
    add("")
    add(", ".join(f"`{c}`" for c in commands()))
    add("")
    return "\n".join(lines) + "\n"


def write(path: Path = OUT) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")
    return path


def is_current(path: Path = OUT) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == render()
