"""Check the checker: put each VBA bug back and prove its test goes red.

Run from pocketbook/: python tools/mutation_check.py. Exits non-zero
if any mutation survives."""
import importlib.util, os, pathlib, subprocess, shutil, sys

# No bytecode is ever written from a mutated file, and any cached bytecode for the file is dropped before and
# after each mutation. Found 26 Sep 2026: Python checks a cached .pyc against the source's size and its mtime in
# whole SECONDS. A mutation that keeps the file's size ("< 2" -> "< 1"), restored within the same second, left
# the mutated bytecode in __pycache__, so the next test run executed the planted bug: a clean checkout read red.
# Two same-size mutations of one file inside a second could likewise run the previous mutant's bytecode.
ENV = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}


def _drop_cache(f: str) -> None:
    pyc = pathlib.Path(importlib.util.cache_from_source(f))
    if pyc.exists():
        pyc.unlink()
E="src/pocketbook/engine.py"; C="src/pocketbook/config.py"; B="src/pocketbook/book.py"
L="src/pocketbook/live.py"
S="src/pocketbook/stats.py"; P="src/pocketbook/perm.py"
K="src/pocketbook/checks.py"; CF="src/pocketbook/confirmatory.py"; PV="src/pocketbook/prevalence.py"
KG="src/pocketbook/kgroups.py"; CT="src/pocketbook/confirm_tab.py"; LA="src/pocketbook/launcher.py"
I="src/pocketbook/ingest.py"; LK="src/pocketbook/look.py"; CO="src/pocketbook/control.py"
HO="src/pocketbook/house.py"; Y="src/pocketbook/settings.yaml"; RS="src/pocketbook/results.py"
RC="src/pocketbook/record.py"; PS="src/pocketbook/prespec.py"
SC="src/pocketbook/scout.py"; CFG="src/pocketbook/config.py"; JT="src/pocketbook/joint.py"
muts = [
 ("1 blank->zero",       E, 'if p is BLANK:\n        return None, "blank"', 'if p is BLANK:\n        return 0.0, None', "test_finding_1"),
 ("2 empty->index 0",    E, 'if rate is None or base is None or base == 0:', 'if base is None or base == 0:\n        return None\n    if rate is None:\n        rate = 0.0\n    if False:', "test_finding_2"),
 ("4 text->0 on top",    E, '                if why_t or why_d:', '                if why_t and not why_d and m.mode == "sumnum":\n                    vals.append((0.0, d)); continue\n                if why_t or why_d:', "test_finding_4"),
 ("8 threshold default", C, '    absent = [k for k in BENCHMARK_KEYS if k not in node]', '    node = {"min_units": 30, "worse_at": 1.25, "better_at": 0.8, "confidence": 0.95, "power": 0.8, **node}\n    absent = [k for k in BENCHMARK_KEYS if k not in node]', "test_finding_8"),
 ("tie-out disabled",    E, '        if not _close(got, want, scale):', '        if False:', "test_the_tie_out"),
 ("unknown keys ignored",C, '        if k not in allowed:', '        if False:', "misspelled"),
 ("judgment pre-chosen", "src/pocketbook/control.py",
  'value=None if s.judgment or rec is None else rec.shown)',
  'value=(rec or s.options[0]).shown)', "waits_for_every_judgment"),
 ("outcome cut by",      E, '    tops = {m.value if m.mode == "sumnum" else m.flag for m in measures if m.is_rate}',
  '    tops = set()', "outcome"),
 ("unconfirmed columns run", C, '        if raw.get("columns_confirmed") is not True:',
  '        if False:', "confirms_it"),
 ("memory ignored", "src/pocketbook/meanings.py",
  '        if hit and hit.get("means") in cat:', '        if False:', "remembered_and_outranks"),
 ("forget forgets nothing", "src/pocketbook/memory.py",
  '        if mem["columns"].pop(n, None) is not None:', '        if mem["columns"].get(n) is None:', "forget_by_name"),
 ("RANR read as a loss", E, '                s.excess = (s.num - top * s.den) if hi == "worse" else (top * s.den - s.num)',
  '                s.excess = s.num - top * s.den', "ranr_is_revenue"),
 ("loss floor ignored",  E, '    if events is not None and higher_is == "worse" and events < min_events:',
  '    if False:', "too_few_losses"),
 ("no allowance for many tests", E, '    if how == "none" or m == 0:', '    if True:', "allowance"),
 ("judged-against ignored", E, '                if bench.compare_to == "peers":', '                if False:', "judged_against"),
 ("materiality ignored", E, '                s.material = s.dollars > 0 and s.dollars >= mat', '                s.material = s.dollars > 0',
  "materiality_as"),
 ("key optional again",  E, '    if config.key not in have:', '    if False:', "missing_key"),
 ("reading on whole-book multiple", E, '                s.reading_topline = reading_of(s.vs_rest, s.units, bench, floor, s.p_book, **kw)',
  '                s.reading_topline = reading_of(s.vs_topline, s.units, bench, floor, s.p_book, **kw)', "big_pocket"),
 # 25 Sep 2026: the third layer, losses against revenue, and the second walk's defects
 ("split not pooled",    E, '        if strata:', '        if False:', "planted_revolving"),
 ("dollar outcome pooled as loan odds", E, '            if m.mode == "flagwt" and m.per == EACH_LOAN:',
  '            if m.mode == "flagwt":', "planted_revolving"),
 ("halves at the book's median", E, '        med = {k: statistics.median(v) for k, v in groups.items()}',
  '        med = {k: statistics.median([x for g in groups.values() for x in g]) for k in groups}', "own_median"),
 ("copied book runs old extract", B, '    if extract is not None:', '    if False:', "copied_workbook"),
 ("forget re-learned",   B, '    if dropped:\n        # a Forget', '    if False:\n        # a Forget', "prunes_the_memory"),
 ("yes kept over new columns", B, 'and not new_cols else None', ' else None', "new_column_takes"),
 ("set up deletes results", B, '            if t in INPUT_TABS or t in HELPERS or t in FOLDED_TABS[:2]:', '            if True:',
  "keeps_the_last_results"),
 ("open workbook not checked", B,
  '    if not _writable(book):\n        return Outcome(False, book, [f"{book.name} is open in Excel. Close it, then press Run',
  '    if False:\n        return Outcome(False, book, [f"{book.name} is open in Excel. Close it, then press Run',
  "open_in_excel"),
 ("edges read as one number", B, 'abs(e) >= 100000', 'abs(e) >= 1e30', "one_number"),
 ("edge range unchecked", B, '        if bad:', '        if False:', "outside_the_columns"),
 ("boxes by 1.00x again", RS, '    if flag in (engine.WORSE, engine.BETTER):\n        worse_is',
  '    if flag in (engine.WORSE, engine.BETTER, engine.UNSURE_WORSE, engine.UNSURE_BETTER):\n        worse_is',
  "boxes_follow"),
 ("split ignores the minimums", E, '            if thin or few:', '            if sh.rate is None or sl.rate is None:',
  "under_the_minimum"),
 ("three-way not built", E, '                three_way.append(three)', '                pass', "three_way_pockets"),
 ("any column splits", B, '        elif cat[code].cut in ("band", "dimension"):', '        elif True:', "cant_split"),
 ("dollar line on every rate", E, '        elif m.name == "gco_rate":', '        elif True:',
  "gco_and_profit or materiality_as"),
 ("forget lasts one run", B, '        if forgotten:\n            # a Forget holds', '        if False:\n            # a Forget holds',
  "forget_holds"),
 ("workbook taken as extract", B, '    if workbook_picked(extract):\n        # the third walk',
  '    if False:\n        # the third walk', "own_extract"),
 ("heat maps colour untested", RS,
  'bv = bk._shown(s.vs_topline, m) if s is not None and s.reading_topline not in untested else None',
  'bv = bk._shown(s.vs_topline, m) if s is not None else None', "leave_out_pockets"),
 ("RANR gap reads or more", RS, '        return -sg * 100', '        return sg * 100', "ranr_is_marked"),
 ("band width ignored",  B, '    far = _band_widths(raw, about.get("_widths") or {}, cfg, table, about.get("_edge_cells"))', '    far = []', "every_20"),
 ("suggestion not worked out", B, '        if about.get("_suggest") and not testing:', '        if False:',
  "suggested_answers"),
 ("edges not remembered", "src/pocketbook/memory.py", '        if text:\n            e["edges"] = text',
  '        if False:\n            e["edges"] = text', "every_20"),
 ("dollars against the book", RS, 'C_COST_D: f"={at(live.P_DOLLARS, RG)}"',
  'C_COST_D: f"={at(live.P_EX_BOOK, RG)}"', "dollars_agree or paid_cost_kept_dollars_are_the_engines"),
 ("untested pockets boxed", RS,
  '        untested = any(s.flag in (engine.THIN, engine.FEW) for s in ss.values())', '        untested = False',
  "dollars_agree"),
 ("three-way without its caveat", RS,
  '                    holds = "Yes" if bk._holds_partner(res, g) else f"No: may be mostly {pt[0]}"',
  '                    holds = None', "holds_fixed"),
 ("luck line at the catch rate", B, '                x = stats.smallest_gap_for(ln, s.units, b.confidence, 0.5)',
  '                x = stats.smallest_gap_for(ln, s.units, b.confidence, b.power)', "luck_alone"),
 ("bands say up to", E, "        first = f(math.floor(lo / step) * step) if lo is not None and lo < edges[0] else None",
  "        first = None", "bands_read_as_ranges"),
 ("grids lose the data range", E, "        labels = band_labels(edges, min(seen), max(seen)) if seen else band_labels(edges)",
  "        labels = band_labels(edges)", "smallest_to_its_largest"),
 ("in use refuses a number", "src/pocketbook/control.py",
  '        lookup = (f"IFERROR(MATCH({K}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0),"\n                  f"MATCH({K}&\\"|\\"&IFERROR(VALUE({C}),{C}),{OPTIONS_SHEET}!$H:$H,0))")',
  '        lookup = f"MATCH({K}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0)"', "number_the_run_takes"),
 ("rest rate from the book", L, 'value=f"={pick(P_REST_BAND, P_REST_BOOK)}")',
  'value=f"={R(P_REST_BOOK)}")', "rest_a_pocket_is_read_against"),
 ("luck side coloured", RS, '            ws.cell(row=rr, column=c, value=f"={at(live.P_FLAG, prow)}")',
  '            ws.cell(row=rr, column=c, value=f\'=SUBSTITUTE({at(live.P_FLAG, prow)},", not significant","")\')',
  "not_significant_is_left_plain or real_loss_keeps"),
 ("negative comparison divided plainly", "src/pocketbook/stats.py",
  '    return ra / rb if rb > 0 else 1 + (ra - rb) / abs(rb)', '    return ra / rb', "negative_comparison"),
 ("blue counts rows", B, '    small = len(set(blue))', '    small = len(blue)', "too_small_to_test_are_pointed"),
 ("fallback called worked out", B, '        lines_ = [k for k in ("worse_at", "better_at") if k in sug and k not in fb]',
  '        lines_ = [k for k in ("worse_at", "better_at") if k in sug]', "nothing_to_work_from"),
 ("category limits ignored", B, '            method[key] = int(got)', '            pass', "category_limits"),
 ("guesses ignore the limits", "src/pocketbook/meanings.py",
  '            elif f.numeric and len(set(f.numbers)) > few_values:', '            elif f.numeric and len(set(f.numbers)) > 12:',
  "category_limits"),
 ("profit by the loss lines", E, '        line = profit_line(bench, materiality_line.get("gco_rate")) if m.in_points else None',
  '        line = None', "same_on_both_tabs or follows_the_profit_line"),
 ("three-way red on unheld rows", RS, '    cf(ws, rng(K_WORSE), [(loose, None, grey, None),\n',
  '    cf(ws, rng(K_WORSE), [\n', "holds_fixed"),
 ("luck not marked", RS, """                          (f'{W}="{live.NOT_SURE}"', CANVAS, None, None),\n""",
  "", "shortfall_is_pink"),
 ("edges leak between workbooks", B, '            if c not in kept["columns"] and cat[code].cut == "band" else None',
  '            if cat[code].cut == "band" else None',
  "edges_stay_out"),
 ("last run not shown", B, '        _last_run_used(wb, res)', '        pass', "last_run_used"),
 ("split luck without the allowance", E, '        if bench is not None:\n            keys = [k for k, got in grid.split_compare.items()',
  '        if False:\n            keys = [k for k, got in grid.split_compare.items()', "carry_the_allowance"),
 ("profit line one number again", E, '    if line.kind == "test":', '    if False:',
  "follows_the_profit_line or judged_by_the_profit_line"),
 ("fallback called worked out", B, '            res.suggest_fallback = fallback', '            pass', "nothing_to_work_from"),
 ("split luck shaded", RS, """                    f = f'=IF({v}="","",IF({live.sig(p)},{v},{words}))'""",
  """                    f = f'=IF({v}="","",{v})'""", "bracketed"),
 ("small material pockets not pointed out", B, '    if small:\n        rows_said', '    if False:\n        rows_said',
  "too_small_to_test"),
 ("start here left stale", B, 'f" \u00b7 last Run {stamp}" if stamp else "")', '"")', "start_here"),
 # NEXT-GOAL 3.15: the pre-spec
 ("pre-spec edited but read as committed", "src/pocketbook/prespec.py",
  '        dirty = bool(status.stdout.strip())', '        dirty = False', "dirty"),
 ("holdout ends left out", "src/pocketbook/prespec.py",
  '        return self.start <= d <= self.end', '        return self.start < d < self.end', "holdout_touch"),
 # OC-34: the add-ons
 ("run on while an add-on is missing", "src/pocketbook/launcher.py",
  '"run": _on(ready)', '"run": "normal"', "set_up_and_run_wait"),
 ("install ok on pip's word", "src/pocketbook/deps.py",
  '    return not still, out', '    return rc == 0, out', "only_ok_when_the_check_after"),
 ("first install unseen until restart", "src/pocketbook/deps.py",
  '            site.addsitedir(user)', '            pass', "seen_without_a_restart"),
 # fix 3.8: the Look tab
 ("look spreads over the code", "src/pocketbook/look.py", '    values = sorted(x for x in nums if x != code)',
  '    values = sorted(nums)', "test_look"),
 # 25 Sep 2026: the tests of docs/statistics.md, rulings OC-34 to OC-37
 ("share of loans unpooled again", S, '    return math.sqrt(max(pbar * (1 - pbar), 0.0) * (1 / n1 + 1 / n2))',
  '    p1, p2 = x1 / n1, x2 / n2\n    return math.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)', "a1_ or family_is_the_inner"),
 ("Fisher one-sided", S, '    return min(1.0, math.fsum(math.exp(v) for v in logs if v <= cut))',
  '    return min(1.0, math.fsum(math.exp(v) for v in logs[k - lo:]))', "fisher"),
 ("shuffle p without the +1", P, '        return (self.hits + 1) / (self.shuffles + 1)', '        return self.hits / self.shuffles',
  "plus_one"),
 ("shuffled across the band", P, '                order = pi if codes is None else pi[np.argsort(codes[pi], kind="stable")]',
  '                order = pi if codes is None else pi[np.argsort(codes, kind="stable")]', "within"),
 ("family counts the totals", E, '    pockets = [k for k in cells if k[0] != ALL and k[1] != ALL]',
  '    pockets = [k for k in cells if k != (ALL, ALL)]', "family_is_the_inner"),
 ("CMH subtracts a half again", S, '    chi = num * num / var', '    chi = (max(abs(num) - 0.5, 0.0)) ** 2 / var',
  "cmh or a5_to_a8"),
 ("fewest loans refuses again", E, '    if not tested and units < min_units:\n        return THIN\n    if events',
  '    if units < min_units:\n        return THIN\n    if events', "walk_6"),
 ("z test below the floor", E, '    if n1 >= floor:', '    if True:', "walk_6"),
 # the firm, 26 Sep 2026 (design.md OC-41): every core, and the same answer however many there are
 ("worker seeded by its share", P, '            pi = order_of(np, n, seed, done + j)',
  '            pi = order_of(np, n, seed + start, done - start + j)', "four_workers"),
 ("a worker's share dropped", P, '        return [f.result() for f in futures]',
  '        return [f.result() for f in futures[:-1]]', "four_workers"),
 ("shares merged out of order", P, '            for part in parts:', '            for part in reversed(parts):',
  "four_workers"),
 ("shares overlap", P, '        at += size', '        at += size - (w % 2)', "four_workers or every_shuffle_once"),
 ("the cores never used", P, '    if workers > 1:\n        try:', '    if False:\n        try:', "four_workers"),
 ("one stream for the whole run", P,
  '    return np.random.Generator(np.random.PCG64(np.random.SeedSequence(seed, spawn_key=(i,)))).permutation(n)',
  '    return np.random.Generator(np.random.PCG64(seed)).permutation(n)', "whoever_deals_it"),
 ("a worker opens the window", "PocketBook.pyw", 'if __name__ == "__main__":', 'if True:', "never_opens_the_window"),
 ("shuffle ties dropped", P, '        self.hits += (~(np.abs(g) < self.thr)).sum(axis=0)',
  '        self.hits += (np.abs(g) > np.abs(self.g)).sum(axis=0)', "exact_tie"),
 # OC-39 (26 Sep 2026): dates are for the pipeline, not the bleed analysis. The loan age filter, the outcome
 # window, the as-of date and the outcome date are gone; the origination date stays (tests/test_dates.py,
 # tests/test_book_dates.py)
 ("dates read one way by default", E, '    if det.ambiguous:', '    if False:', "read_two_ways"),
 ("bad date YAML raises", C, '    except ValueError as exc:\n        # an unquoted',
  '    except KeyError as exc:\n        # an unquoted', "not_a_real_day"),
 ("two origination dates", C, '        if len(hits) > 1:\n            # one column each',
  '        if False:\n            # one column each', "one_column_per_date_role"),
 ("a removed cube line read as unknown", C, '        if k in REMOVED:\n            problems.append(removed_line(k))',
  '        if False:\n            problems.append(removed_line(k))', "removed_line_is_refused"),
 ("a removed meaning read as unknown", C, '        if means in REMOVED:', '        if False:',
  "removed_meaning_on_columns"),
 ("a pre-spec's window read as unknown", "src/pocketbook/prespec.py", '        if k in REMOVED:',
  '        if False:', "pre_spec_with_window_months"),
 ("young and undated loans left out again", E,
  '    rows = table.rows                          # every loan: nothing is left out for its age or dates',
  '    rows = [r for r in table.rows if not config.origination_date or "2000" <= str(r.get(config.origination_date) '
  'or "") <= "2026-06-30"]', "no_loan_is_left_out or no_young_loan"),
 ("no origination line on Check", B, '    rows += _origination_rows(res) + _column_rows(res)',
  '    rows += _column_rows(res)', "origination_dates"),
 ("dates without a reading not counted", E, '            out.unreadable += 1', '            pass',
  "range_of_origination or origination_dates"),
 ("a remembered removed meaning shown as its code", B, '    if entry.get("means") in REMOVED_MEANINGS:',
  '    if False:', "remembered_outcome_date"),
 ("an old Control row read as used", "src/pocketbook/control.py", '        if key in REMOVED_ROWS:',
  '        if False:', "old_control_row"),
 # NEXT-GOAL 3.9 to 3.11: a new column, its period and its meaning (tests/test_derived.py, tests/test_book_dates.py)
 ("new column not made", E, '    table, derived = derive(config, table, warnings)', '    derived = []',
  "one_column_over_another"),
 ("zero bottom not blank", E, '            elif b == 0:', '            elif False:', "zero_or_blank_bottom"),
 ("blank new value read as zero", E, '            r[d.name] = v', '            r[d.name] = 0.0 if v is None else v',
  "zero_or_blank_bottom"),
 ("missing rule skipped on the bottom", E, '        rt, rb = rules.get(d.top), rules.get(d.bottom)',
  '        rt, rb = rules.get(d.top), None', "missing_rule_on_the_bottom"),
 ("new column shadows an extract column", E, '        if d.name in table.columns:\n            raise DataRefused',
  '        if False:\n            raise DataRefused', "named_like_a_column"),
 ("new column from an outcome cut by", E, '            made_from[d.name] = made_from.get(hit, hit)',
  '            pass', "made_from_an_outcome"),
 ("periods never compared", E, '        if pt and pb and pt != pb:', '        if False:', "periods_that_disagree"),
 ("period on a category", C, '            elif means not in AMOUNT_MEANINGS:', '            elif False:',
  "period_is_for_an_amount"),
 ("definition dropped", C, '                definitions[str(col)] = " ".join(d.split())', '                pass',
  "period_is_for_an_amount"),
 ("stale new column runs", B, '        elif made[1] != now:', '        elif False:', "made_on_control"),
 ("new column run before set up", B, '        elif made is None:\n            problems.append',
  '        elif made is None and False:\n            problems.append', "made_on_control"),
 ("Look loses the new column at Run", B, '    look.refresh(wb, res.table or table, res.config.split',
  '    look.refresh(wb, table, res.config.split', "made_on_control or periods_and_meanings"),
 ("new column samples to seventeen figures", B, '            samples = [f"{float(v):.4g}" for v in samples]',
  '            pass', "made_on_control"),
 ("period on Columns not recorded", B, '                entry["period"] = PERIOD_OPTIONS[str(per).strip()]',
  '                pass', "periods_and_meanings"),
 ("ratio plant missing", "src/pocketbook/synth.py",
  '            if not bad or rng.random() < _odds(ratio) / top:', '            if True:', "plants_the_ratio"),
 # NEXT-GOAL 3.1 to 3.6: profit after losses, in points; contribution; the words; the shuffle count
 ("profit back to a multiple", E, '    return None if rate is None or base is None else rate - base',
  '    return index_of(rate, base)', "two_negatives or test_2"),
 ("contribution as RANR less GCO", E, '(t + q, None, top_col) if why_q is None', '(t - q, None, top_col) if why_q is None',
  "contribution_is_ranr_plus_gco or boxes_follow"),
 ("priced for it on the wrong pair", RS,
  'TOGETHER = {("more", "more"): "Priced for it", ("more", "less"): "Net drain", ("less", "more"): "Strong",',
  'TOGETHER = {("less", "more"): "Priced for it", ("more", "less"): "Net drain", ("more", "more"): "Strong",',
  "boxes_follow_the_lines_exactly or priced_pocket"),
 ("shuffle count missing from the Test column", B,
  '        return f"shuffled: {hits:,} of {s.shuffles:,}" if hits is not None else f"{s.shuffles:,} shuffles"',
  '        return f"{s.shuffles:,} shuffles"', "shuffle_count"),
 ("shuffle count from the other comparison", B, '        hits = s.hits_band if peers and not s.alone else s.hits_book',
  '        hits = s.hits_book', "shuffle_count"),
 ("Luck alone back on the tabs", RS, 'K_WORSE: "Worse?", K_P: "p-value",',
  'K_WORSE: "Worse?", K_P: "Luck alone",', "p_value_and_not_significant"),
 ("could be luck back in the readings", E,
  'UNSURE_WORSE, UNSURE_BETTER = "worse, not significant", "better, not significant"',
  'UNSURE_WORSE, UNSURE_BETTER = "worse, but could be luck", "better, but could be luck"',
  "p_value_and_not_significant or luck_gap_keeps"),
 ("profit material by its own total", E, '        elif m.name in PROFIT and gco_line is not None:', '        elif False:',
  "loss_sides_dollar_line or gco_and_profit"),
 ("points line read as dollars", E, '    size = abs(gap) if line.kind == "points" else abs(gap * den)',
  '    size = abs(gap * den)', "judged_by_the_profit_line or follows_the_profit_line"),
 ("split profit as a multiple", E, '            idx = sh.rate - sl.rate if m.in_points else stats.multiple(sh.rate, sl.rate)',
  '            idx = stats.multiple(sh.rate, sl.rate)', "pools_profit"),
 ("split pools profit as a ratio", E, '        if m.in_points:\n            # (O - E) over', '        if False:\n            # (O - E) over',
  "pools_profit"),
 ("smallest profit gap as a multiple", S, '    if ln.method == "difference":\n        return smallest_difference(',
  '    if False:\n        return smallest_difference(', "smallest_profit_gap"),
 ("synthetic RANR ignores losses again", "src/pocketbook/synth.py",
  '        ranr = round(contribution - gco, 2)', '        ranr = round(contribution, 2)', "net_drain or plant_is_the_worst"),
 ("no price for the priced pocket", "src/pocketbook/synth.py",
  '        apr = interest_rate(fico) + (PREMIUM if priced else 0.0)', '        apr = interest_rate(fico)',
  "priced_pocket or plant_is_the_worst"),
 # NEXT-GOAL 3.16 to 3.18: the pocket budget, the families, the product mix (tests/test_checks.py)
 ("budget from every loan", K, '    bad = int(round(res.total.rates[OUTCOME].num))',
  '    bad = int(round(res.total.rates[OUTCOME].units))', "pocket_budget"),
 ("coverage counts untestable pockets", K, '    ok = [c for c in cells if c.rates[OUTCOME].events >= floor]',
  '    ok = cells', "pocket_budget"),
 ("dollar coverage counted in loans", K,
  '    share_d = (sum(c.rates[BOOKED].den for c in ok) / dollars) if dollars else 0.0',
  '    share_d = (sum(c.rows for c in ok) / loans) if loans else 0.0', "pocket_budget"),
 ("over budget not warned", K, '        if n > most:', '        if False:', "more_pockets_than"),
 ("band comparison not a family", K, '                for attr, words in COMPARISONS:',
  '                for attr, words in COMPARISONS[:1]:', "families_are_grids"),
 ("untested rate counted as a family", K, '                    if k:\n                        out.append((kind,',
  '                    if True:\n                        out.append((kind,', "nothing_tested_is_no_family"),
 ("split halves not families", K, '            if k:\n                out.append(("split halves"',
  '            if False:\n                out.append(("split halves"', "halves_as_families"),
 ("a single red read as strong", K, 'So a single red across {n:,} families is weak evidence.',
  'So a single red is strong evidence.', "families_are_grids"),
 ("product cut by still warned", K, '        if col in cut:\n            continue', '        if False:\n            continue',
  "products_cut_by"),
 ("one product warned", K, '        if len(seen) < 2:', '        if len(seen) < 1:', "products_cut_by"),
 ("credit product unnamed", "src/pocketbook/settings.yaml", 'hints: [product, prod_type, loan_type]',
  'hints: []', "credit_product_column"),
 ("Check without the new lines", B, '    rows += checks.rows(res)', '    pass', "check_carries_the_budget"),
 # NEXT-GOAL 3.15 wired: the pre-spec at Run, on Check and in the Log (tests/test_confirmatory.py)
 ("pre-spec cell not read", B, '    held_to = confirmatory.read(wb, book, problems)', '    held_to = None',
  "cannot_use_is_refused"),
 ("a pre-spec with problems runs", CF,
  '            problems.append(f"{cell}: in the pre-spec {p.name}, {_plain(x)}")', '            pass',
  "cannot_use_is_refused"),
 ("set up drops the pre-spec", B,
  '        if key in kept["control"]:\n            choose, own = kept["control"][key]',
  '        if key in kept["control"] and key != control.PRESPEC_KEY:\n            choose, own = kept["control"][key]',
  "cannot_use_is_refused"),
 ("a pre-spec's name read from elsewhere", CF, '        p = Path(book).resolve().parent / p',
  '        p = p.resolve()', "held_to_a_committed"),
 ("deviations not warned", CF, '        out += [("Warning", f"{DEVIATES}: {d}") for d in st.deviations]', '        pass',
  "held_to_a_committed"),
 ("deviating run not labelled", CF, '    elif st.deviations:\n        k = len', '    elif False:\n        k = len',
  "held_to_a_committed"),
 ("holdout touch not logged", CF, '    if st.touched:\n        out.append(f"{HOLDOUT_MARK}',
  '    if False:\n        out.append(f"{HOLDOUT_MARK}', "held_to_a_committed"),
 ("holdout runs not counted", CF,
  '        return sum(1 for _, lines in record.entries(wb) if any(v.startswith(HOLDOUT_MARK) for v in lines))',
  '        return 0 * sum(1 for _, lines in record.entries(wb) if any(v.startswith(HOLDOUT_MARK) for v in lines))',
  "held_to_a_committed"),
 # final check 26 Sep 2026: F5 and F13
 ("run's loans called the holdout", "src/pocketbook/prespec.py",
  '    return said + f"this run used loans made {r.text()}, {tail}."',
  '    return f"The holdout is {r.text()} in this run; the pre-spec says {hold.text()}."',
  "never_called_the_holdout or held_to_a_committed"),
 ("pre-spec groups named without the data", CF, '        ps = st.spec = prespec.named(ps, ranges={c: column_range(res, c) for c in ps.columns})',
  '        pass', "names_the_pre_specs_groups"),
 ("pre-spec written after the run unsaid", CF, '    if st.spec.written > st.ran_on:', '    if False:',
  "written_after_the_run"),
 ("edited pre-spec not said", CF, '    if pv.get("dirty"):', '    if False:', "held_to_a_committed"),
 ("unchecked holdout read as untouched", CF, '        if dates is None:\n            st.unchecked = why',
  '        if dates is None:\n            st.touched = 0', "said_unchecked"),
 ("development loans read as the holdout", CF, '    if ps.holdout.holds(first) and ps.holdout.holds(last):',
  '    if True:', "all_sit_in_the_holdout"),
 ("tested band kept in the strata", CF, '    out["strata"] = [c for c in cut if c != out["column"]]',
  '    out["strata"] = cut', "left_out_of_the_strata"),
 ("tested band not found", CF, '    elif column in [x.field for x in cfg.bands]:', '    elif False:',
  "left_out_of_the_strata"),
 # NEXT-GOAL 3.12: the Prevalence tab (tests/test_prevalence.py)
 ("prevalence halves at the median", PV, 'engine.HIGH if v > med[(b, d)]', 'engine.HIGH if v >= med[(b, d)]',
  "splits_halves"),
 ("prevalence dollars counted as loans", PV, '            got[1] += v', '            got[1] += 1', "splits_halves"),
 ("prevalence without the new columns", PV, '    for d in res.derived:', '    for d in ():', "new_columns_bands"),
 ("prevalence edges made up", PV, '    if not typed:\n        return None, ""', '    if not typed:\n        return (1.0,), "made up"',
  "no_edges_is_said"),
 ("prevalence tie-out off", PV, '        if sum(x[0] for x in out[k].values()) != c.rows:\n            return None',
  '        if False:\n            return None', "does_not_add_up"),
 ("groups not counted on Grids", RS, '    r = _groups(ws, res, views, G, r + 2, left, hid + 4)',
  '    r = r + 2', "count_the_book_by_the_new_columns"),
 ("words run into numbers", RS,
  '                  indent=1 if c in (K_BAND, K_SEG, K_HALF, K_HOLDS) else 0)', '                  indent=0)',
  "words_after_a_number"),
 # 26 Sep 2026: the final check's wording finding, F9 (tests/test_tab_wording.py)
 ("split test named, not explained", B,
  'f"Cochran-Mantel-Haenszel, which asks whether an odds ratio this far from 1 could "\n' + ' ' * 30
  + 'f"come from shuffling loans within their pockets. It has no continuity correction: "\n' + ' ' * 30
  + 'f"nothing is taken off the gap between actual and expected before it is squared."))',
  'f"Cochran-Mantel-Haenszel, with no continuity correction."))', "split_test_asks"),
 ("steady pockets read as proof", B, '"no: bigger in some pockets","no sign they differ")\'',
  '"no: bigger in some pockets","yes")\'', "same_size_says"),
 ("ruling number back on Check", B, '"charge-offs taken out. If RANR nets recoveries instead, "',
  '"charge-offs taken out (OC-35). If RANR nets recoveries instead, "', "no_ruling_number"),
 ("dollar rate answers same size", B, '        return "not tested: dollar rate"', '        return "yes/no outcome only"',
  "same_size_is or same_size_says"),
 ("D3 outlives the check", B, '        head, tail = (re.escape(x) for x in NEW_COLS_NOTE.split("{}"))',
  '        head, tail = "(?!)", "(?!)"', "retires_the_ask"),
 # 26 Sep 2026: the adversarial pass's four findings, fixed (tests/test_adversarial_2026_09_26.py)
 ("the bar not rounded", S, '    return round(1.0 - confidence, 12)', '    return 1.0 - confidence', "at_the_bar"),
 ("Q about the pooled ratio again", S,
  '    centre = math.fsum(w * t for w, t in zip(weights, thetas)) / math.fsum(weights)',
  '    centre = math.log(pooled_or)', "weighted_mean_log_odds"),
 ("no rate read as a zero rate", S, '        if self.loans is None and self.rate is None:', '        if False:',
  "absent_rate"),
 ("unanswered shuffle still named", E, '                if s.p_book is None and s.p_band is None:\n                    s.test = None',
  '                if False:\n                    s.test = None', "could_not_answer"),
 # 26 Sep 2026: one comparison decides the verdict, the dollars and materiality; profit reads literally
 # (tests/test_one_comparison.py)
 ("dollars over the book under the band", E, '                        s.by_band, s.dollars = True, s.excess_band',
  '                        s.by_band, s.dollars = True, s.excess', "one_comparison"),
 ("band dollars against the whole band", E,
  '                    s.excess_band = (s.num - rb * s.den) if hi == "worse" else (rb * s.den - s.num)',
  '                    s.excess_band = (s.num - _rate(cells[(b, ALL)].rates[m.name].sums()) * s.den) if hi == "worse" '
  'else (_rate(cells[(b, ALL)].rates[m.name].sums()) * s.den - s.num)', "by_hand"),
 ("materiality on the book's dollars", E, '            if mat is not None and s.dollars is not None:\n                s.material = s.dollars > 0 and s.dollars >= mat',
  '            if mat is not None and s.excess is not None:\n                s.material = s.excess > 0 and s.excess >= mat',
  "one_comparison"),
 ("ranked by the book's dollars", RS, '            d = s.dollars\n', '            d = s.excess\n',
  "one_comparison"),
 ("the reference dollars hidden", L,
  """                    ws.cell(row=r, column=P_OTHER, value=(\n                        f'=IF({R(P_BY_BAND)}""",
  """                    ws.cell(row=r, column=P_OTHER, value=('=""' or\n                        f'=IF({R(P_BY_BAND)}""",
  "test_2_on_the_workbook"),
 ("Check silent on what decides", B, '        rows.append(("Decides each pocket", decides(res)))', '        pass',
  "one_comparison"),
 ("command line ranks by the book", "src/pocketbook/cli.py",
  '                ranked = sorted(((c.rates[m.name].dollars, k, c) for k, c in g.inner()\n                                 if c.rates[m.name].dollars is not None)',
  '                ranked = sorted(((c.rates[m.name].excess, k, c) for k, c in g.inner()\n                                 if c.rates[m.name].excess is not None)',
  "one_comparison"),
 ("profit verdict word back", L, """    past = (f'IF(LEFT({word},5)="worse","short of ","ahead of ")&""",
  """    past = (f'IF(LEFT({word},5)="worse","keeps less ","keeps more ")&""",
  "one_comparison or test_2_on_the_workbook or priced_pocket"),
 ("literal gap from the other comparison", E,
  '        return literal(s.flag, s.vs_band, s.dollars, "its band", line, s.p_band)',
  '        return literal(s.flag, s.vs_rest, s.dollars, "its band", line, s.p_band)', "one_comparison"),
 ("short and ahead swapped", E, '    side = "short of" if word in (WORSE, UNSURE_WORSE) else "ahead of"',
  '    side = "ahead of" if word in (WORSE, UNSURE_WORSE) else "short of"', "one_comparison"),
 ("not significant dropped from the literal reading", E,
  '    if word in (UNSURE_WORSE, UNSURE_BETTER):\n        out += " (not significant)"',
  '    if False:\n        out += " (not significant)"', "one_comparison or luck_gap_keeps"),
 ("inside the line read as not significant", E, '        if line is None or line.kind == "test":\n            why',
  '        if True:\n            why', "one_comparison"),
 ("profit flag not literal on Where it bleeds", L,
  'f"={literal(R(P_FLAG), R(P_GAP), R(P_P), R(P_DOLLARS), R(P_BY_BAND))}" if m.in_points',
  'f"={R(P_FLAG)}" if m.in_points', "one_comparison or test_2_on_the_workbook or same_on_both_tabs"),
 ("a real shortfall not pink", RS,
  """                          (f'{W}="{live.YES}"', ALERT, Font(color=CRIMSON, bold=True), None),""",
  """                          (f'{W}="{live.YES}"', None, None, None),""", "shortfall_is_pink or holds_fixed"),
 ("lone pocket judged by its empty band", E, '                    if not s.alone:\n                        s.flag = s.reading_band',
  '                    if True:\n                        s.flag = s.reading_band', "alone_in_its_band_is_flagged"),
 ("lone pocket not explained", RS,
  '". It decides the gap, the excess and both verdicts. A pocket alone in its band has nothing beside it "',
  '". It decides the gap, the excess and both verdicts. Nothing beside it "', "alone_in_its_band_is_explained"),
 ("lone note in Together", RS,
  """            f'"{TOGETHER[("more", "same")]}","")))))))')""",
  """            f'"{TOGETHER[("more", "same")]}","alone in its band")))))))')""",
  "together_stays_the_pair"),
 # 26 Sep 2026: what are you running? Each answer's own minimum (tests/test_run_kind.py)
 ("bleed run asks for a date", B, 'NEEDS_COLUMNS = {BLEED: cfgmod.CORE, NEW_VARIABLE:',
  'NEEDS_COLUMNS = {BLEED: cfgmod.CORE + ("origination_date",), NEW_VARIABLE:', "never_asks_for_a_date"),
 ("new variable run without a date", B, 'NEW_VARIABLE: cfgmod.TESTING_CORE + ("origination_date",)}',
  'NEW_VARIABLE: cfgmod.TESTING_CORE}', "needs_an_origination_date or two_origination_dates"),
 ("core column not refused by name", B, '        if len(hits) != 1:\n            who = ',
  '        if False:\n            who = ', "core_column_by_name"),
 ("blank run kind picks for you", "src/pocketbook/control.py",
  '    if chosen in (None, ""):\n        if s.in_launcher:',
  '    if chosen in (None, "") and s.key == "run_kind":\n        found[key] = "bleed"\n        return\n'
  '    if chosen in (None, ""):\n        if s.in_launcher:', "blank_answer_is_refused"),
 ("follow-up never asked", "src/pocketbook/control.py", '            if asked(s, found):\n                _take',
  '            if False:\n                _take', "follow_up_is_refused"),
 ("pre-spec held under a bleed run", B, '    if kind == BLEED:\n        if text is not None:',
  '    if kind == BLEED:\n        if False:', "pre_spec_under_a_bleed_run"),
 ("scouting runs", B, '    if kind == NEW_VARIABLE and step == SCOUT:', '    if False:', "scouting_is_refused"),
 ("lone pocket not counted on Check", K, '    return [("Alone in its band", ',
  '    return []\n    return [("Alone in its band", ', "counts_the_pockets_alone"),
 # 26 Sep 2026: the judging settings live in the workbook (OC-40, tests/test_live.py). Each plants a formula that
 # ignores its setting on Control, reading what the last Run used instead
 ("loss line worse-at not live", L, '    formulas[L_WORSE] = number("worse_at", L_WORSE)',
  '    formulas[L_WORSE] = last[L_WORSE]', "follow_a_change and worse_at"),
 ("loss line better-at not live", L, '    formulas[L_BETTER] = number("better_at", L_BETTER)',
  '    formulas[L_BETTER] = last[L_BETTER]', "follow_a_change and better_at"),
 ("confidence not live", L, '    formulas[L_CONF] = number("confidence", L_CONF)',
  '    formulas[L_CONF] = last[L_CONF]', "follow_a_change and confidence"),
 ("judged against not live", L, """    formulas[L_BAND] = f'=IFERROR({opt("compare_to", c)}="peers",NA())' if c else last[L_BAND]""",
  '    formulas[L_BAND] = last[L_BAND]', "follow_a_change and judged"),
 ("materiality not live", L, """        formulas[L_MKIND] = f'=IF({own_set(d)},"dollars",IFERROR({opt("materiality", c, "L")},NA()))'""",
  '        formulas[L_MKIND] = last[L_MKIND]', "follow_a_change and materiality"),
 ("profit line not live", L, """        formulas[L_PKIND] = (f'=IF({own_set(d)},"points",IFERROR({opt("revenue_line", c, "L")},'""",
  """        formulas[L_PKIND] = last[L_PKIND]\n        (f'=IF({own_set(d)},"points",IFERROR({opt("revenue_line", c, "L")},'""",
  "follow_a_change and profit"),
 ("the live bar not rounded", L, '    formulas[L_BAR] = f"=ROUND(1-C{L_CONF},12)"', '    formulas[L_BAR] = f"=1-C{L_CONF}"',
  "one_rounded_bar"),
 ("1 - confidence inline in a reading", L, '    return f"AND(ISNUMBER({p}),{p}<{BAR})"',
  '    return f"AND(ISNUMBER({p}),{p}<1-confidence)"', "one_rounded_bar"),
 ("a p-value at the bar reads significant", L, '    return f"AND(ISNUMBER({p}),{p}<{BAR})"',
  '    return f"AND(ISNUMBER({p}),{p}<={BAR})"', "exactly_at_the_bar or profit_at_the_bar"),
 # 26 Sep 2026: the confirmatory test, 4b and 4e (tests/test_kgroups.py, tests/test_confirm_test.py)
 ("B3 on K degrees of freedom", KG, '        p_general = stats.chi2_sf(general, len(keep))',
  '        p_general = stats.chi2_sf(general, len(keep) + 1)', "b3_on_k_minus_1 or b3_b4_worked"),
 ("the trend scores unused", KG, '        T += float((s * (n - E)).sum())', '        T += float((n - E).sum())',
  "b3_b4_worked or trend_uses_its_scores"),
 ("the unconditional fit on thin pockets", CF, '    fit = kgroups.conditional_fit(pockets, ref, K)',
  '    fit = kgroups.unconditional_fit(pockets, ref, K)', "fits_conditionally"),
 ("the holdout takes development loans", CF,
  '        which = HOLDOUT if hold.holds(d) else DEVELOPMENT if dev.holds(d) else None',
  '        which = HOLDOUT if (hold.holds(d) or dev.holds(d)) else None',
  "holdout_takes_no_development or holdout_holds_only"),
 ("the reference group ignored", CF, 'groups=tuple(inp.groups), ref=inp.reference_index,',
  'groups=tuple(inp.groups), ref=0,', "reference_group_is_the_pre_specs"),
 ("capture on every loan, not the holdout", CF, '        return concentration(self.holdout)',
  '        return concentration(self.development, self.holdout)', "capture_is_on_the_holdout"),
 ("a pocket under the floor left out of the pooled test", KG,
  '    return [p for p in pockets if p.informative()]',
  '    return [p for p in pockets if p.informative() and p.n >= 30]', "below_every_floor or too_small_to_read"),
 ("the reference deviation back", CF, '    if ran and len(ran) == len(tests):', '    if False:',
  "goal_check_no_longer or range_held_to"),
 ("the holdout line reads the first and last loan", CF, '                "holdout": t.holdout.range}',
  '                "holdout": run_range(res, ps)}', "goal_check_no_longer or range_held_to"),
 ("a stratum not cut by accepted", B, '            if s in cut_by:\n                continue',
  '            if True:\n                continue', "stratum_the_run_does_not_cut"),
 ("the tab's reading not live", CT, """IF({live.sig(ref)},"significant","not significant"))'""",
  """IF({ref}<0.05,"significant","not significant"))'""", "follow_the_confidence"),
 ("the tab's range at 95% always", CT, """_cell(ws, r, c + 2, (f'=TEXT(EXP({b}-{Z}*{se}),"0.00")&"x to "&'""",
  """_cell(ws, r, c + 2, (f'=TEXT(EXP({b}-1.96*{se}),"0.00")&"x to "&'""", "follow_the_confidence"),
 ("a group not significant in the plain line", CT, """pieces.append(f'IF({live.sig(p)},{said}&{rng},"")')""",
  """pieces.append(f'{said}&{rng}')""", "tab_says_what_it_found"),
 # 26 Sep 2026: the redesign's launcher, and suggestions that exist when the workbook is written (test_launcher.py)
 ("the launcher's cut ignored", B, '    skip = {c for c in columns if cut is not None and c not in cut}',
  '    skip = set()', "next_writes_the_choices"),
 ("tested and held fixed at once", LA, '                self.hold = [c for c in self.hold if c != name]       # tested',
  '                pass       # tested', "exclude_each_other"),
 ("a suggestion pre-chosen", B, '        c = ws.cell(row=r[0].row, column=SUGGEST_COL,',
  '        c = ws.cell(row=r[0].row, column=control.CHOOSE_COL,', "suggested_value_is_on_control_before"),
 ("no suggestion until the first Run", B,
  '    worked = _suggest_at_set_up(wb, book, as_read, memory_path, testing=kind_now == NEW_VARIABLE)',
  '    worked = ({}, set())', "suggested_value_is_on_control_before"),
 ("Run leaves the suggestion stale", B,
  '            _suggestions(wb[control.SHEET], *res.suggest_all, when="from this extract at the last Run")',
  '            pass', "run_refreshes_the_suggestion"),
 ("Excel's lock file unseen", B, ' or book.with_name(f"~${book.name}").exists())', ')',
  "while_the_workbook_is_open"),
 ("open at a cell opens anywhere", B, '        sel.activeCell = cell\n', '', "open_at_puts"),
 ("Run on while the workbook is open", LA, 'b.exists() and not self.book_open),', 'b.exists()),',
  "while_the_workbook_is_open"),
 ("the key column tickable", LA, '                if k == "num":\n                    row["a"]',
  '                if k in ("num", "key"):\n                    row["a"]', "key_and_date"),
 ("a refused Run not marked on the rail", LA, '                marks[3] = "blocked"', '                marks[3] = "current"',
  "each_answer_still_needed"),
 ("Set up on with an add-on missing", LA, '        ready = not self.gate.missing and not self.busy',
  '        ready = not self.busy', "add_on_missing_the_rail"),
 ("the open question dropped", B, '            if isinstance(key, str) and key.count("|") == 2 and not r[C_TREAT - 1].value:',
  '            if False:', "finished_run_shows"),
 ("the launcher's column limits ignored", B, '            got = getattr(choices, key)             # chosen',
  '            pass             # chosen', "column_limits_are_chosen"),
 ("a saved shortlist's boxes move", LA, '"c": None, "locked": locked,', '"c": None, "locked": False,',
  "saved_shortlist"),
 ("the outcome tested against unchecked", B, '        if code != "outcome":', '        if False:',
  "outcome_the_launcher_tests"),
 # 26 Sep 2026: Goal 2 item 1, the cliffs planted in the second book (tests/test_generic.py). The first reads
 # dates only as the first book writes them, which the first book's own goal test cannot see; the second forgets
 # the pockets, which the second book's clean copy is built to catch (its worst dealer crowds the lowest group)
 ("dates read only year-month-day", CF, '        return engine._date_reader(table, col, "when each loan was made"), None',
  '        return (lambda raw: __import__("pocketbook.ingest", fromlist=["x"]).parse_date(raw, "%Y-%m-%d")), None',
  "second_books"),
 ("the pockets forgotten", CF, '    return _stratum_labels(res, tuple(ps.strata), res.table.rows)[0]',
  '    return _stratum_labels(res, (), res.table.rows)[0]', "second_book_with_no_cliff"),
 # 26 Sep 2026: Goal 2 item 2, a test of a new variable needs only what it uses (tests/test_run_kind.py,
 # tests/test_generic.py). Each puts the old minimum back, lets the bleed analysis off it, or shows dollars
 # a run doesn't have
 ("new variable run needs the dollar columns again", B, 'NEW_VARIABLE: cfgmod.TESTING_CORE + ("origination_date",)}',
  'NEW_VARIABLE: cfgmod.CORE + ("origination_date",)}', "needs_no_booked_amount"),
 ("the cube file needs the dollar lines on every run", C,
  '    needs = TESTING_CORE if run_kind == "new_variable" else CORE', '    needs = CORE',
  "needs_the_dollar_lines_unless or needs_no_booked_amount"),
 ("the bleed analysis lets the dollar columns go", C,
  '    needs = TESTING_CORE if run_kind == "new_variable" else CORE', '    needs = TESTING_CORE',
  "needs_the_dollar_lines_unless"),
 ("the bleed run's minimum loses the dollar columns", B, 'NEEDS_COLUMNS = {BLEED: cfgmod.CORE, NEW_VARIABLE:',
  'NEEDS_COLUMNS = {BLEED: cfgmod.TESTING_CORE, NEW_VARIABLE:', "still_refuses_an_extract_without_the_dollar"),
 ("set up notes the dollar columns a new variable doesn't use", B,
  '    if kind_now == NEW_VARIABLE:',
  '    if False:', "needs_no_booked_amount"),
 ("4e shows GCO with no GCO column", CF, '    t.dollars = gcol is not None', '    t.dollars = True',
  "needs_no_booked_amount or gco_dollars_only_when"),
 ("4e reads GCO through the booked amount", CF, '    gcol = getattr(cfg, "gco", "") or None',
  '    gcol = next((x.value for x in res.measures if x.name == "gco_rate"), None)', "gco_dollars_only_when"),
 ("4e drops its GCO figures when there are some", CT,
  '        return (loans, flag, bad, capture) + ((gco, gco_capture) if t.dollars else ()) + (rate, lift)',
  '        return (loans, flag, bad, capture) + (rate, lift, None, None)', "capture_is_on_the_holdout"),
 # (retired 27 Sep 2026, redesign phase 4: "a new variable's tabs talk about profit it doesn't have" planted into the
 # lines-in-use sentence on the hidden _live, which the Confirmatory test tab showed and no tab shows now: New
 # variables shows its own lines, and Record's Settings reads each line on its own)
 # (two entries retired here with OC-42: "Prevalence counts booked dollars with no booked amount" and "Losses vs
 # revenue written with nothing to show" planted into tabs only a bleed Run writes now, and a bleed Run always has
 # the booked amount, GCO and RANR, so no Run can reach either line with them missing)
 # 26 Sep 2026: OC-42, a test of a new variable builds no bleed analysis (tests/test_new_variable_run.py)
 ("a new variable builds the grids again", E, '    bleed = config.run_kind != "new_variable"', '    bleed = True',
  "builds_no_grid"),
 ("a new variable runs the shuffle test", E, '    if bleed:\n        _shuffle_tests(', '    if True:\n        _shuffle_tests(',
  "builds_no_grid"),
 ("a new variable writes the bleed tabs", B, '    if bleed_tabs(res):\n        _write_bleed(wb, res, stamp)',
  '    if True:\n        _write_bleed(wb, res, stamp)', "writes_no_bleed_tab"),
 ("an earlier bleed Run's tabs kept", B, '    for t in RESULT_TABS[:-1] + ("Materiality", "Learned"):',
  '    for t in ("Confirmatory test", "Check", "Materiality", "Learned"):', "takes_off_the_ones"),
 ("Check keeps the bleed's rows", B, '        rows = _without_bleed(rows, None)',
  '        pass', "says_so_in_one_line"),
 ("the launcher shows the bleed's tiles", B, '        return {**confirmatory.headline(res), "open": open_qs}',
  '        pass', "launchers_last_step_reads_the_confirmation"),
 ("a group counted worse without being significant", CF, '             and g["p"] < bar]',
  '             and g["p"] < 1]', "launchers_last_step_reads_the_confirmation"),
 ("Start here reads the bleed's tiles", B, '    if _found_value(wb, "kind") == confirm_tab.FOUND_KIND:\n        return',
  '    if False:\n        return', "start_here_shows_each_group"),
 ("Start here's count not live", CT, """f'COUNTIFS({F(1)},"group",{F(G_ODDS)},">1",{F(G_P)},"<"&{live.BAR})'""",
  """f'COUNTIFS({F(1)},"group",{F(G_ODDS)},">1",{F(G_P)},"<0.05")'""", "start_here_shows_each_group"),
 # 26 Sep 2026: Set up does each piece of reading once (tests/test_set_up_once.py)
 ("date gate: no space-padded day", I, r'_N = r" ?\d{1,2}"', r'_N = r"\d{1,2}"',
  "turn_away_nothing or space_padded"),
 ("date gate: %Y%m%d eight digits only", I, r'"%Y%m%d": r"\d{4}\d{1,2} ?\d{1,2}",', r'"%Y%m%d": r"\d{6,8}",',
  "turn_away_nothing or space_padded"),
 ("date gate: case matters", I, "re.compile(rx, re.IGNORECASE | re.DOTALL)", "re.compile(rx, re.DOTALL)",
  "turn_away_nothing or space_padded"),
 ("date gate: one space only", I, r'"%b %d, %Y": rf".+\s+{_N},\s+\d{{4}}",', r'"%b %d, %Y": rf".+ {_N}, \d{{4}}",',
  "turn_away_nothing or space_padded"),
 ("date gate never asked", I, "            if gate(s) is None:", "            if False:", "never_reach_strptime"),
 ("date gate backwards", I, "            if gate(s) is None:", "            if gate(s) is not None:",
  "counts_exactly_what_strptime"),
 ("set up classifies from scratch", B, "    cols = profile.classify(table, few, many, facts_of)",
  "    cols = profile.classify(table, few, many)", "facts_once"),
 ("review works the facts out again", "src/pocketbook/meanings.py",
  "    fs = facts_of(table, known)\n    out: list[Review] = []",
  "    fs = {c: facts(table, c) for c in table.columns}\n    out: list[Review] = []", "facts_once"),
 ("Look reads the numbers again", LK, "    shapes = {c: shape_of(table, c, known.get(c)) for c in columns}",
  "    shapes = {c: shape_of(table, c) for c in columns}", "no_number_set_up"),
 ("handed-down blanks not counted", LK, "known.rows - known.nonblank, known.nonblank - len(known.numbers)",
  "0, known.nonblank - len(known.numbers)", "same_answers"),
 ("settings read on every call", CO, "    if key not in cache:\n        cache[key] = _read_settings(path)",
  "    if True:\n        cache[key] = _read_settings(path)", "settings_yaml_once"),
 ("settings kept after the run", CO, "            _ONCE.cache = outer if outer is None else {}", "            pass",
  "between_two_runs"),
 # 26 Sep 2026: the redesign, phase 2 (the tabs the analyst fills in; tests/test_answer_tabs.py, tests/test_look.py)
 ("Status never waits", CO, """"{SAME}","{WAITING}"),""))'))""", """"{SAME}","{SAME}"),""))'))""", "status_says_waiting"),
 ("waiting tile counts the settled answers", B, """f'=IFERROR(COUNTIF(Status,"{house.WAITING}"),0)',""",
  """f'=IFERROR(COUNTIF(Status,"{house.SAME}"),0)',""", "status_says_waiting"),
 ("materiality panel ignores the level", CO, '        line = f"({share!r}*book_gco)"', '        line = "(book_gco)"',
  "materiality_panel or materiality_level"),
 ("low end bar loses the loans below the slices", LK, """f'={V(S_BELOW)}+SUMIFS(""", """f'=SUMIFS(""",
  "bars_regroup_live or slices_sit"),
 ("bars cut the slices' span, not the range", LK, 'f"=({V(S_TO)}-{V(S_FROM)})/{V(S_N)}"',
  'f"=({V(S_HI)}-{V(S_LO)})/{V(S_N)}"', "bars_regroup_live"),
 ("edges read one late", LK, '{(k - 1) * 99 + 1},99))', '{k * 99 + 1},99))', "red_lines_follow"),
 ("every N starts a step late", LK, 'first = f"(INT({V(S_MIN)}/{step})*{step}+{step})"',
  'first = f"(INT({V(S_MIN)}/{step})*{step}+2*{step})"', "red_lines_follow"),
 ("the mean is the median", LK, '"Mean", statistics.fmean(s.values), fmt=s.fmt)',
  '"Mean", statistics.median(s.values), fmt=s.fmt)', "mean_beside_the_median or numbers_match"),
 ("the code gets no bar of its own", LK, '    if s.code is None or not s.at_code:', '    if True:', "red_bar_of_its_own"),
 ("scatters redrawn at every Run", LK, '    if hs.cell(row=3, column=1).value == _drawn(split, bands):',
  '    if False:', "not_redrawn"),
 ("a Run loads the workbook twice", B, '    raw, problems, about = read_book(book, memory_path, wb=wb)\n    if raw is not None:',
  '    raw, problems, about = read_book(book, memory_path)\n    if raw is not None:', "loads_the_workbook_once"),
 ("a Run saves twice", B, '    summary = _headline(res, wb)', '    summary = _headline(res, wb); _save(wb, book)',
  "loads_the_workbook_once"),
 ("Treat as not read", B, '            answer = str(said).strip().lower() if said not in (None, "") else None',
  '            answer = None', "treat_as_on_columns"),
 ("Forget on Columns ignored", B, 'str(r[C_FORGET - 1].value or "").strip() == FORGET_YES]',
  'str(r[C_FORGET - 1].value or "").strip() == "Never"]', "forget_drops_it or prunes_the_memory"),
 ("the profit line asked of a new variable", Y,
  "        # a test of a new variable reads no profit (the firm's redesign, phase 2): not asked for one\n        only_when: {run_kind: bleed}\n",
  "        # a test of a new variable reads no profit (the firm's redesign, phase 2): not asked for one\n",
  "not_asked_the_profit_line"),
 ("odd values counted with the table's end", B, 'COL_FIRST + 1) - 1 if cols', 'COL_FIRST + 1) if cols',
  "start_here_counts or counted_on_start_here"),
 ("the launcher says cube again", LA, '"4. Press Run. The results land in the workbook."]',
  '"4. Press Run the cube. The results land in the workbook."]', "luck_or_cube"),
 ("title band without its red rule", HO, '        c.border = Border(bottom=_side("thick", rule))',
  '        c.border = Border()', "title_band"),
 ("method note doesn't fold", HO, '    ws.row_dimensions.group(top, r - 1, outline_level=1, hidden=False)', '    pass',
  "title_band"),
 ("Needs a Run drawn as Changes now", HO, '    s = _side("dashed", SLATE)', '    s = _side("thin", INK_TEXT)',
  "three_input_styles"),
 ("Set up's stand-ins left in the workbook", B, '        for cell, v in reversed(changed):\n            cell.value = v',
  '        pass', "refuses_until_answered or nothing_is_picked_for_you"), # 26 Sep 2026: the redesign's phase 3, the result tabs (tests/test_result_tabs.py and the tests repointed to them)
 ("Option A undone: the book's dollars over the whole book", E, '                s.dollars = s.excess_rest\n',
  '                s.dollars = s.excess\n', "judged_against_the_book_counts or by_hand"),
 ("Show ignores Material?", RS, """f'{A(L_MAT)}="{live.YES}"),AND(""", """f'TRUE),AND(""", "below_the_line"),
 ("Pockets ignores its Pockets dropdown", RS, """value=f'=IF(AND({A(L_KIND)}={sel["kind"]},""",
  """value=f'=IF(AND(TRUE,""", "dropdowns_pick_the_rows"),
 ("the caption counts every measure", RS, '''[f"{Lr(L_KIND)},{sel['kind']}", f"{Lr(L_MEAS)},{M}", *crit]''',
  '''[f"{Lr(L_KIND)},{sel['kind']}", *crit]''', "dropdowns_pick_the_rows"),
 ("worse pockets not ranked first", RS, '            key = (held, 0 if s.flag == engine.WORSE and losing else 1,',
  '            key = (held, 0,', "ranks_the_worse_pockets_first or ranks_by_the_deciding_dollars"),
 ("a pocket losing more only against the other comparison left off", RS,
  '            if not ((d is not None and d > 0) or (other is not None and other > 0)):',
  '            if not (d is not None and d > 0):', "follow_a_change_on_control"),
 ("Material? read off the flag", L, """f'=IF({R(P_MATERIAL)}="yes",{q(YES)},IF({R(P_MATERIAL)}="","",{q(NO)}))'""",
  """f'=IF({R(P_FLAG)}="worse",{q(YES)},IF({R(P_MATERIAL)}="","",{q(NO)}))'""",
  "every_live_reading or follow_control_without_a_run"),
 ("Not sure read as Yes", L, "IF({f}={q(engine.UNSURE_WORSE)},{q(NOT_SURE)},", "IF({f}={q(engine.UNSURE_WORSE)},{q(YES)},",
  "every_live_reading or dropdowns_pick_the_rows"),
 ("Strong never read", RS, """IF(AND({g}={B},{k}={B}),'\n""", """IF(FALSE,'\n""", "together_formula_reads"),
 ("Together read on an untested row", RS, """(f'IF(OR({untested}=1,{untested}=""),"",""", """(f'IF(FALSE,"",""",
  "together_formula_reads"),
 ("profit's heat the wrong way round", RS, """IF({kind}="pts",-{cell}/{bound},""", """IF({kind}="pts",{cell}/{bound},""",
  "heat_maps_against_the_book"),
 ("loans shaded red", RS, 'LOANS_STEPS = ((0.2, STONE),', 'LOANS_STEPS = ((0.2, house.HEAT_BAD),', "no_red_or_green"),
 ("vs rest of band from the book", RS, '                    nv = (bk._shown(s.vs_band, m)', '                    nv = (bk._shown(s.vs_rest, m)',
  "four_blocks"),
 ("Grids' loans stuck on the first grid", RS, '            key = xk("G|", (G,), f"|loans|{i}") if what == "loans"',
  '            key = xk("G|", (live.q(gnames[0]),), f"|loans|{i}") if what == "loans"', "four_blocks"),
 ("Split's summary stuck on the first grid", RS, '        ws[R.replace("$", "")] = "=" + match(xk("S|", (G,), f"|sum|{i}"))',
  '        ws[R.replace("$", "")] = "=" + match(xk("S|", (live.q(gnames[0]),), f"|sum|{i}"))', "split_shows"),
 ("every grid holds the partner fixed", RS, '        views.put(f"S|{gname}|chip", [("Holds " if held else "Doesn\'t hold ")',
  '        views.put(f"S|{gname}|chip", [("Holds " if True else "Doesn\'t hold ")', "split_shows or planted_revolving"),
 ("the tiles show the last Run's lines", RS, '    tiles = [("Worse at", "=worse_at", X_FMT),',
  '    tiles = [("Worse at", "=1.25", X_FMT),', "follow_a_change_on_control or follow_control_without_a_run"),
 ("a change waiting for a Run not said", RS, """    n = f'COUNTIF(Status,"{house.WAITING}")'""", '    n = "0"',
  "next_run_changes_nothing"),
 ("the scatter on a plain scale", RS, '    chart.x_axis.scaling.logBase = 10', '    chart.x_axis.scaling.logBase = None',
  "scatter_is_the_grid_picked"),
 ("the scatter drawn from the last Run", RS,
  """        hs.cell(row=k, column=H_X, value=f'=IF(OR({un}<>0,{cost}="",{kept}=""),NA(),{cost})')""",
  """        hs.cell(row=k, column=H_X, value=1.0)""", "stays_as_of_the_run"),
 ("an older workbook keeps the tabs the redesign replaced", B,
  '    for t in results.OLD_TABS + OLD_RESULT_TABS + results.HIDDEN + (results.CHART,):', '    for t in ():',
  "loses_the_tabs_the_redesign_replaced or takes_off_the_ones"),
 ("Paid cost kept reads the kept flag for charge-offs", RS,
  '        for c, prow in ((C_H_FC, RC), (C_H_FG, RG), (C_H_FR, RR)):',
  '        for c, prow in ((C_H_FC, RC), (C_H_FG, RR), (C_H_FR, RG)):', "one_grid_at_a_time or every_live_reading"),
 ("a shortfall shown as a surplus", RS,
  """        short = lambda prow: f'=IF({at(live.P_DOLLARS, prow)}="","",-{at(live.P_DOLLARS, prow)})'""",
  """        short = lambda prow: f'=IF({at(live.P_DOLLARS, prow)}="","",{at(live.P_DOLLARS, prow)})'""",
  "paid_cost_kept_dollars_are_the_engines or test_2_on_the_workbook"),
 ("the Grids' blank not blank", RS, '                    rate.append(s.rate if s is not None else None)',
  '                    rate.append(s.rate if s is not None else 0.0)', "four_blocks"),
 # 27 Sep 2026: the redesign's phase 4, New variables and Record (tests/test_confirm_test.py, tests/test_record.py,
 # tests/test_confirmatory.py, tests/test_new_variable_run.py)
 ("the held-fixed columns left in the plain test", CF, '    return [((), k, y, g) for _, k, y, g in items]',
  '    return list(items)', "without_the_held_fixed_columns"),
 ("Holds up? not live", CT, """IF(AND({live.sig(P)},{same(C_)}),"{YES}","{NO}"))'""",
  """IF(AND({P}<0.05,{same(C_)}),"{YES}","{NO}"))'""", "holds_up_and_still_holds"),
 ("Still holds? read off the test with nothing held fixed", CT,
  """IF(AND({live.sig(J)},{same(H)}),"{YES}","{NO}"))'""", """IF(AND({live.sig(P)},{same(C_)}),"{YES}","{NO}"))'""",
  "holds_up_and_still_holds"),
 ("excess not scaled to the book", CF, '    scale = book_total / hold if hold else None', '    scale = 1.0 if hold else None',
  "excess_is_each_groups"),
 ("Material? ignores the line", CT, 'IF(AND({L}>0,{L}>={line}),', 'IF(AND({L}>0,TRUE),', "excess_is_each_groups"),
 ("a saved shortlist's Found columns shown", CT, '    found_hidden = st is not None', '    found_hidden = False',
  "saved_shortlist_hides_the_found or chart_draws_found"),
 ("the chart's worse line fixed at 1.25", CT, '        ws.cell(row=r, column=LINE_COL, value="=worse_at")',
  '        ws.cell(row=r, column=LINE_COL, value=1.25)', "chart_draws_found"),
 ("a refusal kept off Every Run until the next Run", B, '    if redraw:\n        record.refresh_runs(wb)',
  '    if False:\n        record.refresh_runs(wb)', "refused_run_shows_on_every_run"),
 ("Record's Settings never shaded", B, """        out.append((s.question, now, words.get(s.key), f'=IF({status}="{control.WAITING}",1,0)'))""",
  """        out.append((s.question, now, words.get(s.key), '=0'))""", "settings_has_each_setting"),
 ("a Check line sorted into the wrong section", RC, '    if label.startswith(_LEFT):\n        return LEFT',
  '    if label.startswith(_LEFT):\n        return ADDS', "every_line_check_carried"),
 ("an older workbook's Log thrown away", RC, '        ws = wb[OLD_LOG]\n        ws.title = LOG',
  '        del wb[OLD_LOG]\n        ws = wb.create_sheet(LOG)', "older_workbooks_log"),
 ("a pair's sections end on different rows", RC, '    _rule(ws, r - 1, R_LABEL, R_B)',
  '    _rule(ws, r - 1 - max(0, len(a) - len(b)), R_LABEL, R_B)', "six_sections"),
 ("a pre-spec changed after a held-back run not labelled", CF, '        if held and held[-1][1] != self.fingerprint:',
  '        if False:', "changed_after_a_held_back_run"),
 ("a pre-spec's first reading not recorded", CF, '    if st.first_read:', '    if False:',
  "records_the_pre_spec_when_first_read"),
 ("the held-back runs out of order", CF, '    for when, lines in reversed(record.entries(wb)):',
  '    for when, lines in record.entries(wb):', "records_the_pre_spec_when_first_read or changed_after_a_held_back_run"),
 ("a new variable shown the bleed's settings", CO, '            ws.row_dimensions[r[0].row].hidden = key in by_kind',
  '            ws.row_dimensions[r[0].row].hidden = False', "asked_only_what_it_uses"),
 ("a new variable's Set up suggests from bleed grids", B, '        if testing:\n            got = about.get("_prespec")',
  '        if False:\n            got = about.get("_prespec")', "set_up_builds_no_grid"),
 ("the worse line suggested from nothing", B,
  '    gap = test_gap(t, b.confidence) if t and b is not None else None', '    gap = None',
  "suggested_from_the_confirmations_own_groups"),
 # 27 Sep 2026: Goal 2 item 3, the lean pre-spec: a shortlist of inputs (tests/test_shortlist.py)
 ("the allowance left off a shortlist", CF, '        for (i, k), p in zip(where, engine.adjust(ps, how)):',
  '        for (i, k), p in zip(where, ps):', "allowance_is_benjamini or borderline"),
 ("the allowance taken candidate by candidate", CF, '    tests = [run_test(res, ps, inp, labels) for inp in ps.inputs]\n'
  '    allow(tests, allowance(res))', '    tests = [run_test(res, ps, inp, labels) for inp in ps.inputs]\n'
  '    [allow([t], allowance(res)) for t in tests]', "allowance_is_benjamini"),
 ("the table shows the raw p-value", CT, '        p = side.fit.p[k] if raw_p or not side.allowed else side.allowed[k]',
  '        p = side.fit.p[k]', "one_block_per_candidate or borderline"),
 ("only the first input tested", CF, '    tests = [run_test(res, ps, inp, labels) for inp in ps.inputs]\n',
  '    tests = [run_test(res, ps, inp, labels) for inp in ps.inputs[:1]]\n', "three_inputs"),
 ("the launcher ticks only the first input", LA, '        self.test, self.hold = list(self.spec.columns), list(self.spec.strata)',
  '        self.test, self.hold = [self.spec.column], list(self.spec.strata)', "launcher_fills_test_it"),
 ("the shortlist's outcome not picked", LA, '            self.outcome = self.spec.outcome', '            pass',
  "launcher_fills_test_it"),
 ("an input the run left out not said", PS, """                out.append(f"`{inp.column}` isn't tested {where}; the pre-spec lists it.")""",
  "                pass", "differs_is_said_by_its_column"),
 ("the outcome's deviation not said", PS, '        elif not (isinstance(v, str) and v.strip() == ps.outcome):',
  '        elif False:', "differs_is_said_by_its_column"),
 ("a stratum that is also an input accepted", PS, '            both = [c for c in tested if c in names]',
  '            both = []', "refused_line_by_line"),
 ("an input listed twice accepted", PS, """                problems.append(f"`inputs:` lists {', '.join(twice)} more than once")""",
  "                pass", "refused_line_by_line"),
 ("the strata offered filled in", PS,
  """    "strata": ('strata: "[CONFIRM: the columns to hold fixed, such as [FICO, CHANNEL]; [] for none]"   '""",
  """    "strata": ('strata: [FICO, CHANNEL]   '""", "suggested_and_left_blank"),
 ("the one-column pre-spec read as a shortlist", PS,
  '    listed = "inputs" in raw or not any(k in raw for k in INPUT_KEYS)', '    listed = True',
  "shortlist_of_one or figure_for_figure or committed_example"),
 ("the Candidates tile counts no one", CT, """        cand = f'=IFERROR("{len(ran)} · "&({up})&" hold up","{len(ran)}")'""",
  """        cand = f"{len(ran)}\"""", "tiles_count"),
 ("one chart for every candidate", CT, '    for t, a, b in blocks:\n', '    for t, a, b in blocks[:1]:\n',
  "one_chart_per_candidate"),
 ("the levels panel shown on a new variable", CO, '        ws.column_dimensions[_letter(col)].hidden = new',
  '        ws.column_dimensions[_letter(col)].hidden = False', "control_hides"),
 ("Control's worked-out note the bleed's on a new variable", CO,
  '            ws.cell(row=r, column=3).value = METHOD_NEW[label] if new else said[label]',
  '            ws.cell(row=r, column=3).value = said[label]', "control_hides"),
 ("Start here's rows without their candidate", CT, """        name = (f'={P(G_CAND)}&": "&{P(G_NAME)}' if many else""",
  """        name = (f"={P(G_NAME)}" if many else""", "start_here_lists_every"),
 ("the worse line suggested from the first candidate", B,
  '    for x in (t if isinstance(t, (list, tuple)) else [t]):', '    for x in (t[:1] if isinstance(t, (list, tuple)) else [t]):',
  "suggested_from_every"),
 ("Record says only the first input's test", CF, '    for t in st.tests:\n        out.append(("Confirmatory test"',
  '    for t in st.tests[:1]:\n        out.append(("Confirmatory test"', "record_says_each_input"),
 ("the headline counts the first candidate only", CF, '    for t in _ran(st):\n        h, conc',
  '    for t in _ran(st)[:1]:\n        h, conc', "tiles_count or start_here_lists"),
 # 27 Sep 2026: scouting (Goal 2 item 9)
 ("scouting reads a month of the held-back loans", SC, '    dev = [i for d, i in dated if d < cutoff]',
  '    dev = [i for d, i in dated if d < cutoff + timedelta(days=30)]', "never_reads_the_held_back"),
 # OC-51 (27 Sep 2026): the cutoff on Control replaced the launcher's share; the share is only the suggestion's
 ("the suggested cutoff at half the loans", SC, '    at = dated[max(1, math.ceil(share * len(dated))) - 1]',
  '    at = dated[max(1, math.ceil(0.5 * len(dated))) - 1]', "cutoff_splits_the_loans_exactly"),
 ("the noise floor ignored", SC, '        clears = sc.floor is not None and any(v is not None and v > sc.floor',
  '        clears = sc.floor is not None and any(v is not None and v > -1', "ranks_the_planted"),
 ("the held-fixed columns left out of the second forest", SC, '        Xh = np.column_stack(cols + held_cols)',
  '        Xh = np.column_stack(cols + [np.zeros(len(y))] * len(held_cols))', "with_and_without_the_held"),
 ("correlated pairs never flagged", SC, '            if abs(rho) >= CORRELATED:', '            if abs(rho) > 1:',
  "correlated_pair"),
 ("the strata filled in when nothing is held fixed", SC,
  """    strata = f"[{', '.join(sc.hold)}]" if sc.hold else CONFIRM_STRATA""",
  '''    strata = f"[{', '.join(sc.hold)}]" if sc.hold else "[]"''', "nothing_held_fixed"),
 ("an edited pre-spec written over", SC, '    if p.is_file():\n        now = p.read_text',
  '    if False:\n        now = p.read_text', "edit_after_the_held_back"),
 ("the reference not the median's group", SC, '    return bisect.bisect_right(list(bins), float(np.median(seen)))',
  '    return 0', "reference_holds_the_median"),
 ("a bend cut on any wobble", SC, '                if abs(ml - mr) < STEP * mean:', '                if abs(ml - mr) < 0:',
  "steps_cut"),
 ("the edge at the midpoint, never the forest's splits", SC, '    if inside:\n        half', '    if False:\n        half',
  "edge_sits"),
 ("a sliver of a group kept", SC, '        if not small:\n            break', '        if True:\n            break',
  "sliver"),
 ("each fold's forest trains on the loans it scores", SC, '        rf = _forest(seed).fit(X[~va], y[~va])',
  '        rf = _forest(seed).fit(X, y)', "ranks_the_planted"),
 ("Found hidden on a run that scouted", CT, '    found_hidden = st is not None and not st.scouted',
  '    found_hidden = st is not None', "found_shown"),
 ("scouting not logged", B, '         + scout_tab.log_lines(res)             # Goal 2 item 9',
  '         + []             # Goal 2 item 9', "logged_before"),
 ("finding runs without scikit-learn", B, '        why = scout.missing()\n        if why:',
  '        why = None\n        if why:', "without_scikit_learn"),
 ("a new variable with nothing held fixed refused by the engine", E,
  '    if (not keep_b or not keep_d) and config.run_kind != "new_variable":', '    if (not keep_b or not keep_d):',
  "nothing_held_fixed"),
 ("a new variable with nothing held fixed refused by the cube file", CFG,
  '    nothing_held = run_kind == "new_variable"', '    nothing_held = False', "nothing_held_fixed"),
 ("the launcher never offers scikit-learn", LA, '        if "scikit-learn" in self.gate.optional:',
  '        if False:', "offers_scikit_learn"),
 ("the lowest group named below its own values", E,
  '        if dec and lo is not None and lo < edges[0] and edges[0] - step < lo and d < 6:', '        if False:',
  "named_from_its_own"),
 ("a reference named from the run's values not recognised", PS,
  '        named = band_labels(tuple(bins), lo, hi)', '        named = band_labels(tuple(bins))',
  "named_from_its_own or logged_before"),
 # 27 Sep 2026, Goal 3 item 1: renamed PocketBook, and what a machine kept under the old name still read
 ("an old-name workbook's answers dropped", B, '    return old if not book.exists() and old.exists() else book',
  '    return book', "old_name"),
 ("an old-name workbook taken as the extract", B, '    for suffix in (SUFFIX, OLD_SUFFIX):',
  '    for suffix in (SUFFIX,):', "either_name"),
 ("the old folder's files ignored", "src/pocketbook/places.py",
  '    return old if not new.exists() and old.exists() else new', '    return new', "old_folder"),
 ("the old memory variable ignored", "src/pocketbook/memory.py",
  '    return os.environ.get(ENV) or os.environ.get(OLD_ENV) or None', '    return os.environ.get(ENV) or None',
  "old_environment"),
 # 27 Sep 2026, Goal 3 item 2: the analyst's walk through the launcher, both run kinds (docs/walkthrough/2026-09-27)
 ('a pre-spec changed after a held-back run reads as followed', CF,
  '    if h.get("changed"):\n        return "Changed"',
  '    if False:\n        return "Changed"', 'changed_or_just_written'),
 ('a pre-spec this Run wrote reads as followed', CF,
  '    if h.get("written"):',
  '    if False:', 'changed_or_just_written'),
 ('New variables silent on a changed pre-spec', CT,
  '    changed = getattr(st, "changed_after", None) is not None',
  '    changed = False', 'changed_or_just_written'),
 ('a Run that stopped called an answer needed', LA,
  '            self.answers = bool(out.problems)',
  '            self.answers = True', 'run_that_stopped'),
 ('a failed tie-out said as a crash', LA,
  '    except TieOutError as exc:',
  '    except KeyError as exc:', 'run_that_stopped'),
 ("the answers needed out of the workbook's order", LA,
  'self.needs = in_order(needs_of(out.problems))',
  'self.needs = (needs_of(out.problems))', 'top_to_bottom'),
 ("a workbook that won't open says nothing", LA,
  '    except OSError as exc:\n        return (f"Couldn\'t open',
  '    except ArithmeticError as exc:\n        return (f"Couldn\'t open', 'cannot_be_opened'),
 ('an install that worked said in red', LA,
  '            self.note, self.message = self.gate.lines()[:1], []',
  '            self.message, self.note = self.gate.lines()[:1], []', 'install_that_worked'),
 ('one add-on said for three', LA,
  '    them = "it is" if len(missing) == 1 else "they are"',
  '    them = "it is"', 'counts_the_add_ons'),
 ('Record names the measures its own way', B,
  '    title = measure_name',
  '    title = lambda m: m.title', 'names_each_measure'),
 ('a dollar curve to four places', "src/pocketbook/scout_tab.py",
  '    return "#,##0" if top >= 100 else "0.####"',
  '    return "0.####"', 'dollar_column_as_whole'),
 ("the launcher's tile doesn't name the column", LA,
  '    return ((f"{h[\'column\']} groups worse than {h[\'reference\']}"',
  '    return ((f"Groups worse than {h[\'reference\']}"', 'launchers_last_step'),
 ('Start here says the loans tested in other words', CT,
  '    ws.append(["loans", f"{h[\'development\']:,} found · {h[\'holdout\']:,} held back"])',
  '    ws.append(["loans", f"{h[\'development\']:,} on development, {h[\'holdout\']:,} on the holdout"])', 'words_new_variables_uses'),
 ('the bar clock sets a line that is gone', LA,
  '    if optional or line is None or not line.winfo_exists():',
  '    if line is None:', 'bar_clock'),
 # 27 Sep 2026: the firm's answers to the walk's design calls, A to K, and tenet T2 (a check figure only where it can
 # fail); tests/test_firm_answers_2026_09_27.py, and K in tests/test_scout.py
 ("A: a launcher change never waits for a Run", CO,
  '    for r in range(c_top + 1, end - 1):\n        key = ws.cell(row=r, column=KEY_COL).value',
  '    for r in range(0):\n        key = ws.cell(row=r, column=KEY_COL).value', 'changed_in_the_launcher_waits'),
 ("A: a new kind of run counted once for every row it changes", CO,
  """                f'=IF({kind}="{WAITING}","",{status})')""", """                f"={status}")""",
  'changed_in_the_launcher_waits'),
 ("A: what the launcher chose not kept for Status", B,
  '    for r in control.launcher_rows_of(ws):\n        own =', '    for r in []:\n        own =',
  'changed_in_the_launcher_waits'),
 ("B: the tie-out tile back on the finished screen", LA,
  """             f"in those {_s(worse, 'pocket')}", "KEY_RED", "INK"))""",
  """             f"in those {_s(worse, 'pocket')}", "KEY_RED", "INK"), ("Tie-out checks", "1 / 1", "", "INK", "POSITIVE"))""",
  'tie_out_figure_that_could_only'),
 ("B: Record's tie-outs as n of n", B, '            ("Tie-out checks", f"{res.tie_outs:,}: every grid adds up to the book")]',
  '            ("Tie-out checks", f"{res.tie_outs:,} of {res.tie_outs:,} agree: every grid adds up to the book")]',
  'tie_out_figure_that_could_only'),
 ("T2: the Run's first line says the tie-outs agree", B, '    return f"Ran on {res.rows:,} loans from {src.name}."',
  '    return f"Ran on {res.rows:,} loans from {src.name}; {res.tie_outs:,} tie-out checks agree."',
  'tie_out_figure_that_could_only'),
 ("C: charge-offs worse beside kept the same has no name", RS, '    ("more", "same"): "Losing more, profit holding"}',
  '    ("more", "unused"): "Losing more, profit holding"}', 'losing_more_profit_holding'),
 ("C: the formula never reads losing more, profit holding", RS, "IF(AND({g}={W},{same_k}),'",
  "IF(AND({g}={W},{same_k},FALSE),'", 'losing_more_profit_holding'),
 ("D: Start here lists pockets that are only worse or only material", B,
  """value=f'=IF(AND({P(live.P_WORSE, prow)}="{live.YES}",'""",
  """value=f'=IF(OR({P(live.P_WORSE, prow)}="{live.YES}",'""", 'lists_only_the_pockets_worse'),
 ("D: Start here's list smallest dollars first", B, '    for _, band, seg, loans, prow in sorted(top, key=lambda t: t[0]):',
  '    for _, band, seg, loans, prow in sorted(top, key=lambda t: t[0], reverse=True):', 'lists_only_the_pockets_worse'),
 ("E: Start here's count leaves out Checked every column", B,
  """                      f'+IF(Columns!{CONFIRM_CELL.replace("C", "$C$")}="Yes",0,1)', "Control and Columns"),""",
  """                      f'', "Control and Columns"),""", 'give_one_count'),
 ("E: the launcher counts the tabs, not the answers", B, """    lines.append(f"Next: {_n(len(left), 'answer')} needed""",
  """    lines.append(f"Next: {_n(len(on), 'answer')} needed""", 'give_one_count'),
 ("F: a term used without its meaning", LA,
  '        elif re.search(r"\\b" + term + r"s?\\b", said):\n            out.append(meaning)',
  '        elif re.search(r"\\b" + term + r"s?\\b", said):\n            pass', 'what_each_term_means'),
 ("G: Comes to has no worked-out value before the first Run", B,
  '            ws.cell(row=r[0].row, column=control.WORKED_COL).value = v', '            pass',
  'comes_to_shows_the_worked_out'),
 ("G: Comes to shows the option's words before the first Run", CO,
  """        return f'IFERROR(TEXT({key},"0.00")&"×",{before})'""",
  """        return f'IFERROR(TEXT({key},"0.00")&"×",{plain})'""", 'comes_to_shows_the_worked_out'),
 ("H: Look draws the outcome columns", B,
  '    shown = [c for c in shown + [m.name for m in made if m.name not in shown] if c in banded]',
  '    shown = [c for c in shown + [m.name for m in made if m.name not in shown]]', 'look_draws_only'),
 ("I: Start here's odds don't say what is held fixed", CT, """(f", {held} held fixed" if held else "")""", '""',
  'odds_hold_the_columns_fixed'),
 ("J: the finished screen gets none of the Run's lines", B, '    summary["first"] = first_lines(lines)',
  '    summary["first"] = []', 'finished_screen_shows_the_runs_first'),
 ("J: a changed pre-spec left off the finished screen", B,
  '    return (start + [x for x in lines if x.startswith(confirmatory.CHANGED)]', '    return (start + []',
  'finished_screen_shows_the_runs_first'),
 ("K: the candidates' header printed over the pre-spec", "src/pocketbook/scout_tab.py", '    _ = first_row, last_row\n',
  '    ws.print_title_rows = f"{head}:{head}"\n    _ = first_row, last_row\n', 'prints_without_the_candidates'),
 # 27 Sep 2026: the kit as one script to paste, because the bank lets only text in
 ("paste not checked", "tools/bank_kit.py", 'if hashlib.sha256(text.encode("utf-8")).hexdigest() != want:',
  'if False:', "one_line_changed"),
 ("paste cut short accepted", "tools/bank_kit.py", 'if end is None or len(files) != end:', 'if False:', "cut_short"),
 # 27 Sep 2026: Choose tests in the order the analyst works down it, and nothing in an outcome row's boxes
 ("Choose tests in the extract's order", LA,
  'for c in sorted(self.read.columns if self.read else (), key=lambda c: GROUP.get(c.kind, LAST)):',
  'for c in (self.read.columns if self.read else ()):', "choose_tests_rows"),
 ("categories above the number columns", LA, 'GROUP = {"num": 0, "cat": 1, "out": 2, "outd": 2}',
  'GROUP = {"num": 1, "cat": 0, "out": 2, "outd": 2}', "choose_tests_rows"),
 ("a group sorted by name, not the extract's order", LA, 'key=lambda c: GROUP.get(c.kind, LAST)):',
  'key=lambda c: (GROUP.get(c.kind, LAST), c.name)):', "choose_tests_rows"),
 # headless on purpose: CI has no display, so a bug only the window test sees would read MISSED there
 ("the table says every measure again", LA,
  '                if k == "cat":\n                    row["b"] = {"on": c.name in self.seg, "radio": False}',
  '                if k == "cat":\n                    row["b"] = {"on": c.name in self.seg, "radio": False}\n'
  '                if k == "out":\n                    row["every"] = True', "choose_tests_rows_run_numbers"),
 ("no gap between the groups", LA,
  '            row["gap_before"] = bool(out) and out[-1]["group"] != row["group"]',
  '            row["gap_before"] = False', "gaps_fall_where_a_group_starts"),
 ("the gaps push the last row out of sight", LA, 'GAP = 6 ', 'GAP = 10 ', "gaps_fall_where_a_group_starts"),
 # OC-51 (27 Sep 2026, Goal 4): a cutoff the analyst picks, the tree checked on later loans, the shortlist together
 ("the cutoff's own day held back from the tree", SC, '    dev = [i for d, i in dated if d < cutoff]',
  '    dev = [i for d, i in dated if d <= cutoff]', "cutoff_splits_the_loans_exactly"),
 ("the cutoff asked for a saved shortlist instead", Y, '        only_when: {run_kind: new_variable, new_variable_step: scout}',
  '        only_when: {run_kind: new_variable, new_variable_step: prespec}', "blank_cutoff_waits"),
 ("the suggestion's counts take in the cutoff's own day", B, '            before = sum(1 for d in dates if d < got)',
  '            before = sum(1 for d in dates if d <= got)', "blank_cutoff_waits"),
 ("the tree checked on its own development loans", SC, '        if d is None or d < sc.cutoff:\n            continue\n        y = ',
  '        if d is None or d >= sc.cutoff:\n            continue\n        y = ', "out_of_time_auc"),
 ("a category's values renumbered on the held-back loans", SC,
  '    cols = [_values(res, rows, n, kinds[n], sc.levels.get(n))[0] for n in sc.forests["names"]]',
  '    cols = [_values(res, rows, n, kinds[n], None)[0] for n in sc.forests["names"]]', "out_of_time_auc or development_numbering"),
 ("the tree's check never run", B, '        scout.out_of_time(res, sc)\n', '        pass\n', "out_of_time_check_is_recorded"),
 ("the tree reads the held-back loans before the pre-spec is answered", B,
  '        return res.scout_waits\n    # OC-51: the pre-spec is on disk', '        pass\n    # OC-51: the pre-spec is on disk',
  "strata_wait_for_an_answer"),
 ("runs that touched the holdout counted by the line", CF,
  '        return sum(1 for _, lines in record.entries(wb) if any(v.startswith(HOLDOUT_MARK) for v in lines))',
  '        return sum(1 for _, lines in record.entries(wb) for v in lines if v.startswith(HOLDOUT_MARK))',
  "out_of_time_check_is_recorded or edit_after_the_held_back"),
 ("the tree's check not logged", B, '         + scout_tab.held_back_lines(res)       # OC-51',
  '         + []       # OC-51', "out_of_time_check_is_recorded"),
 ("taking a candidate out takes nothing out", JT, '            without = _fit(cells, terms, [x for x in use if x != i])',
  '            without = _fit(cells, terms, use)', "planted_inputs_and_tenure_adds_nothing or scikit_learns_on_a_design"),
 ("the pockets not held fixed together", JT, '        X[r, where[k[0]]] = 1.0', '        X[r, 0] = 1.0',
  "scikit_learns_on_a_design"),
 ("a group with no bad loan fitted anyway", JT, '                elif b == 0 or b == n:', '                elif False:',
  "a_group_with_no_bad_loan"),
 ("a group holding another's loans not caught", JT, '        if got > rank:', '        if True:',
  "same_loans_as_another"),
 ("a solver that broke down said another way", JT,
  '        return _Fit(0.0, {}, {}, False, gone, len(pockets), loans, bad, quiet, DIDNT_SETTLE)',
  '        return _Fit(0.0, {}, {}, False, gone, len(pockets), loans, bad, quiet, "the regression couldn\'t be solved")',
  "solver_that_breaks_down"),
 ("a fit that ran off printed", JT, '    if not settled or wild:', '    if False:', "fit_that_ran_off"),
 ("a reference with no bad loan compared with", JT, '        if n == 0 or b == 0 or b == n:', '        if n == 0:',
  "reference_with_no_bad_loan"),
 ("thin pockets given a constant each", JT, '    if full.pockets and full.bad / full.pockets < MIN_BAD_PER_POCKET:',
  '    if full.pockets and full.bad / full.pockets < 0:', "too_thin"),
 ("no allowance across the shortlist", JT, '    adjusted = engine.adjust([t.p_lr for t in terms], j.allowance)',
  '    adjusted = [t.p_lr for t in terms]', "planted_inputs_and_tenure_adds_nothing"),
 ("a candidate's test on every group, the reference's too", JT,
  '        t.df = sum(1 for g in range(K) if g != t.ref and t.beta[g] is not None)', '        t.df = K',
  "planted_inputs_and_tenure_adds_nothing"),
 ("a near copy never flagged", JT, '            if abs(rho) >= scout.CORRELATED:', '            if abs(rho) > 1:',
  "near_copy"),
 ("the pair's partner left off the tab", CT,
  '                _cell(ws, r, J_WITH, ", ".join(f"{n} ({rho:+.2f})" for n, rho in t.partners), h="left")',
  '                _cell(ws, r, J_WITH, "", h="left")', "near_copy"),
 ("New variables not led by the tree", CT, '    r = _unseen(ws, res, r)\n', '', "leads_with_the_tree"),
 ("Adds? reads the wrong way", CT,
  """IF({live.sig(P)},"{YES}","{NO}"))', bold=True)""",
  """IF({live.sig(P)},"{NO}","{YES}"))', bold=True)""", "leads_with_the_tree"),
 ("Status says Same beside a blank answer", CO,
  """(f'=IF(OR(NOT({asked}),{answered_blank}),"",IFERROR(IF('""",
  """(f'=IF(OR(NOT({asked}),False),"",IFERROR(IF('""", "cutoff_is_asked_only_when_scouting"),
 ("the test of all together left off Record", CF, '    if j is not None and len(ran) > 1:',
  '    if False:', "planted_inputs_and_tenure_adds_nothing"),
 # Codex on #394, 28 Sep 2026: values that are not finite numbers, and two columns with one name
 ("NaN in the extract read as a number", I, '    return f if math.isfinite(f) else Bad("non-numeric", value)',
  '    return f', "not_a_finite_number"),
 ("two columns of one name read as one", I, '    if twice:\n        raise ValueError(', '    if False:\n        raise ValueError(',
  "two_columns_of_one_name"),
 ("a setting of .nan taken as a number", CFG,
  '    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)',
  '    return isinstance(v, (int, float)) and not isinstance(v, bool)', "nan_or_infinity_is_refused"),
 # the tie-out of 28 Sep 2026: a pocket with too few losses given a p-value and counted in the allowance
 ("an untested pocket counted in the allowance", E, '            if hi == "worse" and s.events < bench.min_events:\n                s.p_book = s.p_band = None',
  '            if False:\n                s.p_book = s.p_band = None', "not_counted_in_the_allowance"),
 # the public-data rehearsal, 29 Sep 2026: a category limit off the launcher's list written where only a listed
 # option is read
 ("a limit off the list written as a pick", CO,
  '                r[OWN_COL - 1].value = None if listed[key] is not None else getattr(got, key)',
  '                r[OWN_COL - 1].value = None\n                if listed[key] is None:\n'
  '                    r[CHOOSE_COL - 1].value = getattr(got, key)', "off_the_launchers_list"),
 # and the conditional likelihood multiplying out every coefficient, exact zeros and all (191 s a pocket)
 ("the coefficient at m paired the wrong way round", KG, '    return float(np.dot(a[lo: hi + 1], b[s - hi: s - lo + 1][::-1]))',
  '    return float(np.dot(a[lo: hi + 1], b[s - hi: s - lo + 1]))', "conditional_likelihood_is_unchanged"),
 ("every coefficient multiplied out again", KG, '        o, pmf = _trim(0, np.exp(logpmf))',
  '        o, pmf = 0, np.exp(logpmf)', "sba_stratum_takes_seconds"),
 # and scikit-learn installed but blocked by the machine's policy: the Run crashed on the forest's import
 ("a blocked scikit-learn not loaded before finding", SC,
  '        import sklearn.ensemble  # noqa: F401\n        import sklearn.metrics  # noqa: F401',
  '        pass', "wont_load_is_said_in_words"),
]
LIMIT = 600                  # seconds one planted bug's tests may take


def main() -> int:
    bad = 0
    for name, f, old, new, sel in muts:
        src = open(f).read(); assert src.count(old) == 1, name     # exactly the one place the bug went back
        shutil.copy(f, f + ".bak"); open(f, "w").write(src.replace(old, new, 1))
        _drop_cache(f)
        try:
            # a planted bug that makes its test hang is not caught: it would stall CI for hours instead
            # --assert=plain: only pass or fail matters here. Under CI, pytest stops shortening a failure's
            # explanation, and spelling out a big comparison took past ten minutes ("worker seeded by its share")
            r = subprocess.run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "--assert=plain",
                                "-k", sel],
                               capture_output=True, text=True, env=ENV, timeout=LIMIT)
            said = (r.stdout.strip().splitlines() or r.stderr.strip().splitlines() or ["(pytest said nothing)"])[-1]
            # pytest exits 5 when the selector matched no test: nothing ran, so nothing was caught
            caught = r.returncode not in (0, 5)
        except subprocess.TimeoutExpired:
            said, caught = f"still running after {LIMIT // 60} minutes, stopped", False
        finally:
            shutil.move(f + ".bak", f)
            _drop_cache(f)
        bad += not caught
        print(("CAUGHT " if caught else "MISSED ") + name, "|", said, flush=True)
    return bad


def shard(items: list, arg: str | None) -> list:
    """`k/n` keeps every n-th bug starting at the k-th (k counted from 0), so n CI jobs
    together put back every bug exactly once and each finishes well inside a job's time limit."""
    if not arg:
        return items
    k, n = (int(x) for x in arg.split("/"))
    if not 0 <= k < n:
        raise SystemExit(f"--shard {arg}: the first number must be 0 to {n - 1}")
    return items[k::n]


if __name__ == "__main__":
    if "--shard" in sys.argv:
        muts = shard(muts, sys.argv[sys.argv.index("--shard") + 1])
        print(f"putting back {len(muts)} of the bugs (shard {sys.argv[sys.argv.index('--shard') + 1]})")
    sys.exit(main())
