import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);

function readSource(path) {
  return readFileSync(resolve(root, path), 'utf8');
}

function stripModuleSyntax(source) {
  return source
    .replace(/import\s+\{[\s\S]*?\}\s+from\s+['"][^'"]+['"];\n/g, '')
    .replace(/import\s+[^;]+;\n/g, '')
    .replace(/export\s+/g, '');
}

const sources = ['src/models.js', 'src/workflows.js', 'src/outputs.js', 'src/app.js']
  .map((file) => `// ${file}\n${stripModuleSyntax(readSource(file))}`)
  .join('\n\n');

const bundle = `// Generated by scripts/build-browser.js. Do not edit directly.\n// This classic script bundle lets index.html run from file:// without ES module loading.\n(() => {\n'use strict';\n\n${sources}\n})();\n`;

writeFileSync(resolve(root, 'src/browser-app.js'), bundle);
