"""Check the checker: put each VBA bug back and prove its test goes red.

Run from origination-cube/: python tools/mutation_check.py. Exits non-zero
if any mutation survives."""
import importlib.util, os, pathlib, subprocess, shutil, sys

# No bytecode is ever written from a mutated file, and any cached bytecode for the file is dropped before and
# after each mutation. Found 26 Sep 2026: Python checks a cached .pyc against the source's size and its mtime in
# whole SECONDS. A mutation that keeps the file's size ("< 2" -> "< 1"), restored within the same second, left
# the mutated bytecode in __pycache__, so the next test run executed the planted bug: a clean checkout read red.
# Two same-size mutations of one file inside a second could likewise run the previous mutant's bytecode.
ENV = {**os.environ, "PYTHONDONTWRITEBYTECODE": "1"}


def _drop_cache(f: str) -> None:
    pyc = pathlib.Path(importlib.util.cache_from_source(f))
    if pyc.exists():
        pyc.unlink()
E="src/origination_cube/engine.py"; C="src/origination_cube/config.py"; B="src/origination_cube/book.py"
S="src/origination_cube/stats.py"; P="src/origination_cube/perm.py"
K="src/origination_cube/checks.py"; CF="src/origination_cube/confirmatory.py"; PV="src/origination_cube/prevalence.py"
muts = [
 ("1 blank->zero",       E, 'if p is BLANK:\n        return None, "blank"', 'if p is BLANK:\n        return 0.0, None', "test_finding_1"),
 ("2 empty->index 0",    E, 'if rate is None or base is None or base == 0:', 'if base is None or base == 0:\n        return None\n    if rate is None:\n        rate = 0.0\n    if False:', "test_finding_2"),
 ("4 text->0 on top",    E, '                if why_t or why_d:', '                if why_t and not why_d and m.mode == "sumnum":\n                    vals.append((0.0, d)); continue\n                if why_t or why_d:', "test_finding_4"),
 ("8 threshold default", C, '    absent = [k for k in BENCHMARK_KEYS if k not in node]', '    node = {"min_units": 30, "worse_at": 1.25, "better_at": 0.8, "confidence": 0.95, "power": 0.8, **node}\n    absent = [k for k in BENCHMARK_KEYS if k not in node]', "test_finding_8"),
 ("tie-out disabled",    E, '        if not _close(got, want, scale):', '        if False:', "test_the_tie_out"),
 ("unknown keys ignored",C, '        if k not in allowed:', '        if False:', "misspelled"),
 ("judgment pre-chosen", "src/origination_cube/control.py",
  'value=None if s.judgment or rec is None else rec.shown)',
  'value=(rec or s.options[0]).shown)', "waits_for_every_judgment"),
 ("outcome cut by",      E, '    tops = {m.value if m.mode == "sumnum" else m.flag for m in measures if m.is_rate}',
  '    tops = set()', "outcome"),
 ("unconfirmed columns run", C, '        if raw.get("columns_confirmed") is not True:',
  '        if False:', "confirms_it"),
 ("memory ignored", "src/origination_cube/meanings.py",
  '        if hit and hit.get("means") in cat:', '        if False:', "remembered_and_outranks"),
 ("forget forgets nothing", "src/origination_cube/memory.py",
  '        if mem["columns"].pop(n, None) is not None:', '        if mem["columns"].get(n) is None:', "forget_by_name"),
 ("RANR read as a loss", E, '                s.excess = (s.num - top * s.den) if hi == "worse" else (top * s.den - s.num)',
  '                s.excess = s.num - top * s.den', "ranr_is_revenue"),
 ("loss floor ignored",  E, '    if events is not None and higher_is == "worse" and events < min_events:',
  '    if False:', "too_few_losses"),
 ("no allowance for many tests", E, '    if how == "none" or m == 0:', '    if True:', "allowance"),
 ("judged-against ignored", E, '                if bench.compare_to == "peers":', '                if False:', "judged_against"),
 ("materiality ignored", E, '                s.material = s.excess > 0 and s.excess >= mat', '                s.material = s.excess > 0',
  "materiality_as"),
 ("key optional again",  E, '    if config.key not in have:', '    if False:', "missing_key"),
 ("reading on whole-book multiple", E, '                s.reading_topline = reading_of(s.vs_rest, s.units, bench, floor, s.p_book, **kw)',
  '                s.reading_topline = reading_of(s.vs_topline, s.units, bench, floor, s.p_book, **kw)', "big_pocket"),
 # 25 Sep 2026: the third layer, losses against revenue, and the second walk's defects
 ("split not pooled",    E, '        if strata:', '        if False:', "planted_revolving"),
 ("dollar outcome pooled as loan odds", E, '            if m.mode == "flagwt" and m.per == EACH_LOAN:',
  '            if m.mode == "flagwt":', "planted_revolving"),
 ("halves at the book's median", E, '        med = {k: statistics.median(v) for k, v in groups.items()}',
  '        med = {k: statistics.median([x for g in groups.values() for x in g]) for k in groups}', "own_median"),
 ("copied book runs old extract", B, '    if extract is not None:', '    if False:', "copied_workbook"),
 ("forget re-learned",   B, '    if dropped:\n        # a Forget', '    if False:\n        # a Forget', "learned_tab_prunes"),
 ("yes kept over new columns", B, 'and not new_cols else None', ' else None', "new_column_takes"),
 ("set up deletes results", B, '            if t in INPUT_TABS or t in HELPERS:', '            if True:', "keeps_the_last_results"),
 ("open workbook not checked", B, '    if not _writable(book):', '    if False:', "open_in_excel"),
 ("edges read as one number", B, 'abs(e) >= 100000', 'abs(e) >= 1e30', "one_number"),
 ("edge range unchecked", B, '        if bad:', '        if False:', "outside_the_columns"),
 ("boxes by 1.00x again", B, '    return "more" if idx >= hi else "less" if idx <= lo else "same"',
  '    return "more" if idx > 1 else "less"', "boxes_follow"),
 ("split ignores the minimums", E, '            if thin or few:', '            if sh.rate is None or sl.rate is None:',
  "under_the_minimum"),
 ("three-way not built", E, '                three_way.append(three)', '                pass', "three_way_pockets"),
 ("any column splits", B, '            if cat[code].cut in ("band", "dimension"):', '            if True:', "cant_split"),
 ("dollar line on every rate", E, '        elif m.name == "gco_rate":', '        elif True:',
  "gco_and_profit or materiality_as"),
 ("forget lasts one run", B, '    if forgotten and "Columns" in wb.sheetnames:', '    if False:', "forget_holds"),
 ("workbook taken as extract", B, '    if extract.name.endswith(" - Origination Cube.xlsx"):', '    if False:',
  "own_extract"),
 ("heat maps colour untested", B, '_shown(s.vs_topline, m) if s.reading_topline not in untested',
  '_shown(s.vs_topline, m) if True', "leave_out_pockets"),
 ("RANR gap reads or more", B, """('0.00" pts or less"' if m.in_points else""", """('0.00" pts or more"' if m.in_points else""",
  "ranr_is_marked"),
 ("band width ignored",  B, '    far = _band_widths(raw, about.get("_widths") or {}, cfg, table, about.get("_edge_cells"))', '    far = []', "every_20"),
 ("suggestion not worked out", B, '        if about.get("_suggest"):', '        if False:', "suggested_answers"),
 ("edges not remembered", "src/origination_cube/memory.py", '        if text:\n            e["edges"] = text',
  '        if False:\n            e["edges"] = text', "every_20"),
 ("dollars against the book", B, '            parent = g.cells[(bl, engine.ALL)] if band else res.total',
  '            parent = res.total', "dollars_agree"),
 ("untested pockets boxed", B, '            untested = bool(set(flags.values()) & set(untested_words))',
  '            untested = False', "dollars_agree"),
 ("three-way without its caveat", B, '        note = (lambda g: _three_way_note(res, g)) if res.config.split[1] == "own_median" else None',
  '        note = None', "holds_fixed"),
 ("luck line at the catch rate", B, '                x = stats.smallest_gap_for(ln, s.units, b.confidence, 0.5)',
  '                x = stats.smallest_gap_for(ln, s.units, b.confidence, b.power)', "luck_alone"),
 ("bands say up to", E, "        first = f(math.floor(lo / step) * step) if lo is not None and lo < edges[0] else None",
  "        first = None", "bands_read_as_ranges"),
 ("grids lose the data range", E, "        labels = band_labels(edges, min(seen), max(seen)) if seen else band_labels(edges)",
  "        labels = band_labels(edges)", "boxes_follow"),
 ("in use refuses a number", "src/origination_cube/control.py",
  '        lookup = (f"IFERROR(MATCH({H}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0),"\n                  f"MATCH({H}&\\"|\\"&IFERROR(VALUE({C}),{C}),{OPTIONS_SHEET}!$H:$H,0))")',
  '        lookup = f"MATCH({H}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0)"', "number_the_run_takes"),
 ("rest rate from the book", B, '_rest_rate(s, parent.rates[k]), _shown(gaps[k], ms[k])',
  '_rest_rate(s, res.total.rates[k]), _shown(gaps[k], ms[k])', "boxes_follow"),
 ("luck side coloured", B, '            shown = {k: None if untested or unsure[k] else sides[k] for k in sides}',
  '            shown = {k: None if untested else sides[k] for k in sides}', "luck_gap_keeps"),
 ("negative comparison divided plainly", "src/origination_cube/stats.py",
  '    return ra / rb if rb > 0 else 1 + (ra - rb) / abs(rb)', '    return ra / rb', "negative_comparison"),
 ("blue counts rows", B, '    small = len(set(blue))', '    small = len(blue)', "too_small_to_test_are_pointed"),
 ("fallback called worked out", B, '        lines_ = [k for k in ("worse_at", "better_at") if k in sug and k not in fb]',
  '        lines_ = [k for k in ("worse_at", "better_at") if k in sug]', "nothing_to_work_from"),
 ("category limits ignored", B, '            method[key] = int(got)', '            pass', "category_limits"),
 ("guesses ignore the limits", "src/origination_cube/meanings.py",
  '            elif f.numeric and len(set(f.numbers)) > few_values:', '            elif f.numeric and len(set(f.numbers)) > 12:',
  "category_limits"),
 ("profit by the loss lines", E, '        line = profit_line(bench, materiality_line.get("gco_rate")) if m.in_points else None',
  '        line = None', "same_on_both_tabs or follows_the_profit_line"),
 ("three-way red on unheld rows", B,
  """    red = 'AND($Q5="worse",LEFT($S5,3)<>"no:")' if note_of else '$Q5="worse"'""",
  """    red = '$Q5="worse"'""", "three_way_rows_say"),
 ("luck not marked", B, '            unsure["gco_rate"] = (sides["gco_rate"] != "same" and not real(ps["gco_rate"])',
  '            unsure["gco_rate"] = (False and not real(ps["gco_rate"])', "luck_gap_keeps"),
 ("edges leak between workbooks", B, '            if c not in kept["columns"] and cat[code].cut == "band" else None',
  '            if cat[code].cut == "band" else None',
  "edges_stay_out"),
 ("last run not shown", B, '        _last_run_used(wb[control.SHEET], res)', '        pass', "last_run_used"),
 ("split luck without the allowance", E, '        if bench is not None:\n            keys = [k for k, got in grid.split_compare.items()',
  '        if False:\n            keys = [k for k, got in grid.split_compare.items()', "carry_the_allowance"),
 ("profit line one number again", E, '    if line.kind == "test":', '    if False:',
  "follows_the_profit_line or judged_by_the_profit_line"),
 ("fallback called worked out", B, '            res.suggest_fallback = fallback', '            pass', "nothing_to_work_from"),
 ("split luck shaded", B, '                if stats.significant(got[1], conf):', '                if True:', "bracketed"),
 ("small material pockets not pointed out", B, '    if small:\n        rows_said', '    if False:\n        rows_said',
  "too_small_to_test"),
 ("start here left stale", B, 'else f"{stamp}: {lines[0]}")', 'else stamp)', "start_here"),
 # NEXT-GOAL 3.15: the pre-spec
 ("pre-spec edited but read as committed", "src/origination_cube/prespec.py",
  '        dirty = bool(status.stdout.strip())', '        dirty = False', "dirty"),
 ("holdout ends left out", "src/origination_cube/prespec.py",
  '        return self.start <= d <= self.end', '        return self.start < d < self.end', "holdout_touch"),
 # OC-34: the add-ons
 ("run on while an add-on is missing", "src/origination_cube/launcher.py",
  '"run": _on(ready)', '"run": "normal"', "set_up_and_run_wait"),
 ("install ok on pip's word", "src/origination_cube/deps.py",
  '    return not still, out', '    return rc == 0, out', "only_ok_when_the_check_after"),
 ("first install unseen until restart", "src/origination_cube/deps.py",
  '            site.addsitedir(user)', '            pass', "seen_without_a_restart"),
 # fix 3.8: the Look tab
 ("look spreads over the code", "src/origination_cube/look.py", '    values = sorted(x for x in nums if x != code)',
  '    values = sorted(nums)', "test_look"),
 # 25 Sep 2026: the tests of docs/statistics.md, rulings OC-34 to OC-37
 ("share of loans unpooled again", S, '    return math.sqrt(max(pbar * (1 - pbar), 0.0) * (1 / n1 + 1 / n2))',
  '    p1, p2 = x1 / n1, x2 / n2\n    return math.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)', "a1_ or family_is_the_inner"),
 ("Fisher one-sided", S, '    return min(1.0, math.fsum(math.exp(v) for v in logs if v <= cut))',
  '    return min(1.0, math.fsum(math.exp(v) for v in logs[k - lo:]))', "fisher"),
 ("shuffle p without the +1", P, '        return (self.hits + 1) / (self.shuffles + 1)', '        return self.hits / self.shuffles',
  "plus_one"),
 ("shuffled across the band", P, '                order = pi if codes is None else pi[np.argsort(codes[pi], kind="stable")]',
  '                order = pi if codes is None else pi[np.argsort(codes, kind="stable")]', "within"),
 ("family counts the totals", E, '    pockets = [k for k in cells if k[0] != ALL and k[1] != ALL]',
  '    pockets = [k for k in cells if k != (ALL, ALL)]', "family_is_the_inner"),
 ("CMH subtracts a half again", S, '    chi = num * num / var', '    chi = (max(abs(num) - 0.5, 0.0)) ** 2 / var',
  "cmh or a5_to_a8"),
 ("fewest loans refuses again", E, '    if not tested and units < min_units:\n        return THIN\n    if events',
  '    if units < min_units:\n        return THIN\n    if events', "walk_6"),
 ("z test below the floor", E, '    if n1 >= floor:', '    if True:', "walk_6"),
 ("shuffle ties dropped", P, '        self.hits += (~(np.abs(g) < self.thr)).sum(axis=0)',
  '        self.hits += (np.abs(g) > np.abs(self.g)).sum(axis=0)', "exact_tie"),
 # OC-39 (26 Sep 2026): dates are for the pipeline, not the bleed analysis. The loan age filter, the outcome
 # window, the as-of date and the outcome date are gone; the origination date stays (tests/test_dates.py,
 # tests/test_book_dates.py)
 ("dates read one way by default", E, '    if det.ambiguous:', '    if False:', "read_two_ways"),
 ("bad date YAML raises", C, '    except ValueError as exc:\n        # an unquoted',
  '    except KeyError as exc:\n        # an unquoted', "not_a_real_day"),
 ("two origination dates", C, '        if len(hits) > 1:\n            # one column each',
  '        if False:\n            # one column each', "one_column_per_date_role"),
 ("a removed cube line read as unknown", C, '        if k in REMOVED:\n            problems.append(removed_line(k))',
  '        if False:\n            problems.append(removed_line(k))', "removed_line_is_refused"),
 ("a removed meaning read as unknown", C, '        if means in REMOVED:', '        if False:',
  "removed_meaning_on_columns"),
 ("a pre-spec's window read as unknown", "src/origination_cube/prespec.py", '        if k in REMOVED:',
  '        if False:', "pre_spec_with_window_months"),
 ("young and undated loans left out again", E,
  '    rows = table.rows                          # every loan: nothing is left out for its age or dates',
  '    rows = [r for r in table.rows if not config.origination_date or "2000" <= str(r.get(config.origination_date) '
  'or "") <= "2026-06-30"]', "no_loan_is_left_out or no_young_loan"),
 ("no origination line on Check", B, '    rows += _origination_rows(res) + _column_rows(res)',
  '    rows += _column_rows(res)', "origination_dates"),
 ("dates without a reading not counted", E, '            out.unreadable += 1', '            pass',
  "range_of_origination or origination_dates"),
 ("a remembered removed meaning shown as its code", B, '            elif code in REMOVED_MEANINGS:',
  '            elif False:', "remembered_outcome_date"),
 ("an old Control row read as used", "src/origination_cube/control.py", '        if key in REMOVED_ROWS:',
  '        if False:', "old_control_row"),
 # NEXT-GOAL 3.9 to 3.11: a new column, its period and its meaning (tests/test_derived.py, tests/test_book_dates.py)
 ("new column not made", E, '    table, derived = derive(config, table, warnings)', '    derived = []',
  "one_column_over_another"),
 ("zero bottom not blank", E, '            elif b == 0:', '            elif False:', "zero_or_blank_bottom"),
 ("blank new value read as zero", E, '            r[d.name] = v', '            r[d.name] = 0.0 if v is None else v',
  "zero_or_blank_bottom"),
 ("missing rule skipped on the bottom", E, '        rt, rb = rules.get(d.top), rules.get(d.bottom)',
  '        rt, rb = rules.get(d.top), None', "missing_rule_on_the_bottom"),
 ("new column shadows an extract column", E, '        if d.name in table.columns:\n            raise DataRefused',
  '        if False:\n            raise DataRefused', "named_like_a_column"),
 ("new column from an outcome cut by", E, '            made_from[d.name] = made_from.get(hit, hit)',
  '            pass', "made_from_an_outcome"),
 ("periods never compared", E, '        if pt and pb and pt != pb:', '        if False:', "periods_that_disagree"),
 ("period on a category", C, '            elif means not in AMOUNT_MEANINGS:', '            elif False:',
  "period_is_for_an_amount"),
 ("definition dropped", C, '                definitions[str(col)] = " ".join(d.split())', '                pass',
  "period_is_for_an_amount"),
 ("stale new column runs", B, '        elif made[1] != now:', '        elif False:', "made_on_control"),
 ("new column run before set up", B, '        elif made is None:\n            problems.append',
  '        elif made is None and False:\n            problems.append', "made_on_control"),
 ("Look loses the new column at Run", B, '        look.refresh(book, res.table or table, res.config.split',
  '        look.refresh(book, table, res.config.split', "made_on_control"),
 ("new column samples to seventeen figures", B, '            samples = [f"{float(v):.4g}" for v in samples]',
  '            pass', "made_on_control"),
 ("period on Columns not recorded", B, '                entry["period"] = PERIOD_OPTIONS[str(per).strip()]',
  '                pass', "periods_and_meanings"),
 ("ratio plant missing", "src/origination_cube/synth.py",
  '            if not bad or rng.random() < _odds(ratio) / top:', '            if True:', "plants_the_ratio"),
 # NEXT-GOAL 3.1 to 3.6: profit after losses, in points; contribution; the words; the shuffle count
 ("profit back to a multiple", E, '    return None if rate is None or base is None else rate - base',
  '    return index_of(rate, base)', "two_negatives or test_2"),
 ("contribution as RANR less GCO", E, '(t + q, None, top_col) if why_q is None', '(t - q, None, top_col) if why_q is None',
  "contribution_is_ranr_plus_gco or boxes_follow"),
 ("priced for it on the wrong pair", B,
  'TOGETHER = {("more", "more"): "priced for it", ("more", "less"): "net drain", ("less", "less"): "safe but idle"}',
  'TOGETHER = {("less", "more"): "priced for it", ("more", "less"): "net drain", ("less", "less"): "safe but idle"}',
  "boxes_follow_the_lines_exactly or priced_pocket"),
 ("shuffle count missing from the Test column", B,
  '        return f"shuffled: {hits:,} of {s.shuffles:,}" if hits is not None else f"{s.shuffles:,} shuffles"',
  '        return f"{s.shuffles:,} shuffles"', "shuffle_count"),
 ("shuffle count from the other comparison", B, '        hits = s.hits_band if peers and not s.alone else s.hits_book',
  '        hits = s.hits_book', "shuffle_count"),
 ("Luck alone back on the tabs", B, '"Vs rest of book", "p-value", "Vs rest of band", "p-value",',
  '"Vs rest of book", "Luck alone", "Vs rest of band", "Luck alone",', "p_value_and_not_significant"),
 ("could be luck back in the readings", E,
  'UNSURE_WORSE, UNSURE_BETTER = "worse, not significant", "better, not significant"',
  'UNSURE_WORSE, UNSURE_BETTER = "worse, but could be luck", "better, but could be luck"',
  "p_value_and_not_significant or luck_gap_keeps"),
 ("profit material by its own total", E, '        elif m.name in PROFIT and gco_line is not None:', '        elif False:',
  "loss_sides_dollar_line or gco_and_profit"),
 ("points line read as dollars", E, '    size = abs(gap) if line.kind == "points" else abs(gap * den)',
  '    size = abs(gap * den)', "judged_by_the_profit_line or follows_the_profit_line"),
 ("split profit as a multiple", E, '            idx = sh.rate - sl.rate if m.in_points else stats.multiple(sh.rate, sl.rate)',
  '            idx = stats.multiple(sh.rate, sl.rate)', "pools_profit"),
 ("split pools profit as a ratio", E, '        if m.in_points:\n            # (O - E) over', '        if False:\n            # (O - E) over',
  "pools_profit"),
 ("smallest profit gap as a multiple", S, '    if ln.method == "difference":\n        return smallest_difference(',
  '    if False:\n        return smallest_difference(', "smallest_profit_gap"),
 ("synthetic RANR ignores losses again", "src/origination_cube/synth.py",
  '        ranr = round(contribution - gco, 2)', '        ranr = round(contribution, 2)', "net_drain or plant_is_the_worst"),
 ("no price for the priced pocket", "src/origination_cube/synth.py",
  '        apr = interest_rate(fico) + (PREMIUM if priced else 0.0)', '        apr = interest_rate(fico)',
  "priced_pocket or plant_is_the_worst"),
 # NEXT-GOAL 3.16 to 3.18: the pocket budget, the families, the product mix (tests/test_checks.py)
 ("budget from every loan", K, '    bad = int(round(res.total.rates[OUTCOME].num))',
  '    bad = int(round(res.total.rates[OUTCOME].units))', "pocket_budget"),
 ("coverage counts untestable pockets", K, '    ok = [c for c in cells if c.rates[OUTCOME].events >= floor]',
  '    ok = cells', "pocket_budget"),
 ("dollar coverage counted in loans", K,
  '    share_d = (sum(c.rates[BOOKED].den for c in ok) / dollars) if dollars else 0.0',
  '    share_d = (sum(c.rows for c in ok) / loans) if loans else 0.0', "pocket_budget"),
 ("over budget not warned", K, '        if n > most:', '        if False:', "more_pockets_than"),
 ("band comparison not a family", K, '                for attr, words in COMPARISONS:',
  '                for attr, words in COMPARISONS[:1]:', "families_are_grids"),
 ("untested rate counted as a family", K, '                    if k:\n                        out.append((kind,',
  '                    if True:\n                        out.append((kind,', "nothing_tested_is_no_family"),
 ("split halves not families", K, '            if k:\n                out.append(("split halves"',
  '            if False:\n                out.append(("split halves"', "halves_as_families"),
 ("a single red read as strong", K, 'So a single red across {n:,} families is weak evidence.',
  'So a single red is strong evidence.', "families_are_grids"),
 ("product cut by still warned", K, '        if col in cut:\n            continue', '        if False:\n            continue',
  "products_cut_by"),
 ("one product warned", K, '        if len(seen) < 2:', '        if len(seen) < 1:', "products_cut_by"),
 ("credit product unnamed", "src/origination_cube/settings.yaml", 'hints: [product, prod_type, loan_type]',
  'hints: []', "credit_product_column"),
 ("Check without the new lines", B, '    rows += checks.rows(res)', '    pass', "check_carries_the_budget"),
 # NEXT-GOAL 3.15 wired: the pre-spec at Run, on Check and in the Log (tests/test_confirmatory.py)
 ("pre-spec cell not read", B, '    held_to = confirmatory.read(wb, book, problems)', '    held_to = None',
  "cannot_use_is_refused"),
 ("a pre-spec with problems runs", CF,
  '            problems.append(f"{cell}: in the pre-spec {p.name}, {_plain(x)}")', '            pass',
  "cannot_use_is_refused"),
 ("set up drops the pre-spec", B,
  'control.write_prespec(wb, kept["control"].get(control.PRESPEC_KEY, (None, None))[0])',
  'control.write_prespec(wb)', "cannot_use_is_refused"),
 ("a pre-spec's name read from elsewhere", CF, '        p = Path(book).resolve().parent / p',
  '        p = p.resolve()', "held_to_a_committed"),
 ("deviations not warned", CF, '        out += [("Warning", f"{DEVIATES}: {d}") for d in st.deviations]', '        pass',
  "held_to_a_committed"),
 ("deviating run not labelled", CF, '    elif st.deviations:\n        k = len', '    elif False:\n        k = len',
  "held_to_a_committed"),
 ("holdout touch not logged", CF, '    if st.touched:\n        out.append(f"{HOLDOUT_MARK}',
  '    if False:\n        out.append(f"{HOLDOUT_MARK}', "held_to_a_committed"),
 ("holdout runs not counted", CF, '        return sum(1 for (v,) in wb["Log"]', '        return 0 * sum(1 for (v,) in wb["Log"]',
  "held_to_a_committed"),
 # final check 26 Sep 2026: F5 and F13
 ("run's loans called the holdout", "src/origination_cube/prespec.py",
  '    return said + f"this run used loans made {r.text()}, {tail}."',
  '    return f"The holdout is {r.text()} in this run; the pre-spec says {hold.text()}."',
  "never_called_the_holdout or held_to_a_committed"),
 ("pre-spec groups named without the data", CF, '        ps = st.spec = prespec.named(ps, *column_range(res, ps.column))',
  '        pass', "names_the_pre_specs_groups"),
 ("pre-spec written after the run unsaid", CF, '    if st.spec.written > st.ran_on:', '    if False:',
  "written_after_the_run"),
 ("edited pre-spec not said", CF, '    if pv.get("dirty"):', '    if False:', "held_to_a_committed"),
 ("unchecked holdout read as untouched", CF, '        if dates is None:\n            st.unchecked = why',
  '        if dates is None:\n            st.touched = 0', "said_unchecked"),
 ("development loans read as the holdout", CF, '    if ps.holdout.holds(first) and ps.holdout.holds(last):',
  '    if True:', "all_sit_in_the_holdout"),
 ("tested band kept in the strata", CF, '    out["strata"] = [c for c in cut if c != out["column"]]',
  '    out["strata"] = cut', "left_out_of_the_strata"),
 ("tested band not found", CF, '    elif ps.column in [x.field for x in cfg.bands]:', '    elif False:',
  "left_out_of_the_strata"),
 # NEXT-GOAL 3.12: the Prevalence tab (tests/test_prevalence.py)
 ("prevalence halves at the median", PV, 'engine.HIGH if v > med[(b, d)]', 'engine.HIGH if v >= med[(b, d)]',
  "splits_halves"),
 ("prevalence dollars counted as loans", PV, '            got[1] += v', '            got[1] += 1', "splits_halves"),
 ("prevalence without the new columns", PV, '    for d in res.derived:', '    for d in ():', "new_columns_bands"),
 ("prevalence edges made up", PV, '    if not typed:\n        return None, ""', '    if not typed:\n        return (1.0,), "made up"',
  "no_edges_is_said"),
 ("prevalence tie-out off", PV, '        if sum(x[0] for x in out[k].values()) != c.rows:\n            return None',
  '        if False:\n            return None', "does_not_add_up"),
 ("prevalence tab not written", B, '    prevalence.write(wb, res)', '    pass', "prevalence_tab_counts"),
 ("words run into numbers", B, '            for col in (11, 17, 19):\n                ws.cell(row=r, column=col).alignment = Alignment(indent=1)',
  '            for col in ():\n                pass', "words_after_a_number"),
 # 26 Sep 2026: the final check's wording finding, F9 (tests/test_tab_wording.py)
 ("split test named, not explained", B,
  'f"Cochran-Mantel-Haenszel, which asks whether an odds ratio this far from 1 could "\n' + ' ' * 30
  + 'f"come from shuffling loans within their pockets. It has no continuity correction: "\n' + ' ' * 30
  + 'f"nothing is taken off the gap between actual and expected before it is squared."))',
  'f"Cochran-Mantel-Haenszel, with no continuity correction."))', "split_test_asks"),
 ("steady pockets read as proof", B, '        return "no sign they differ" if not stats.significant(steady, conf)',
  '        return "yes" if not stats.significant(steady, conf)', "same_size_says"),
 ("ruling number back on Check", B, '"charge-offs taken out. If RANR nets recoveries instead, "',
  '"charge-offs taken out (OC-35). If RANR nets recoveries instead, "', "no_ruling_number"),
 ("dollar rate answers same size", B, '        return "not tested: dollar rate"', '        return "yes/no outcome only"',
  "same_size_is or same_size_says"),
 ("D3 outlives the check", B, '    elif "Columns" in wb.sheetnames:\n        # a Run needs C3 = Yes',
  '    elif False:\n        # a Run needs C3 = Yes', "retires_the_ask"),
 # 26 Sep 2026: the adversarial pass's four findings, fixed (tests/test_adversarial_2026_09_26.py)
 ("the bar not rounded", S, '    return round(1.0 - confidence, 12)', '    return 1.0 - confidence', "at_the_bar"),
 ("Q about the pooled ratio again", S,
  '    centre = math.fsum(w * t for w, t in zip(weights, thetas)) / math.fsum(weights)',
  '    centre = math.log(pooled_or)', "weighted_mean_log_odds"),
 ("no rate read as a zero rate", S, '        if self.loans is None and self.rate is None:', '        if False:',
  "absent_rate"),
 ("unanswered shuffle still named", E, '                if s.p_book is None and s.p_band is None:\n                    s.test = None',
  '                if False:\n                    s.test = None', "could_not_answer"),
 ("lone pocket judged by its empty band", E, '                    if not s.alone:\n                        s.flag = s.reading_band',
  '                    if True:\n                        s.flag = s.reading_band', "alone_in_its_band_is_flagged"),
 ("lone pocket's row says nothing", B, '            if peers and s.alone:\n                said = f"{said}; {ALONE}"',
  '            if False:\n                said = f"{said}; {ALONE}"', "alone_in_its_band_says_why"),
 ("lone pocket not counted on Check", K, '    return [("Alone in its band", ',
  '    return []\n    return [("Alone in its band", ', "counts_the_pockets_alone"),
]
def main() -> int:
    bad = 0
    for name, f, old, new, sel in muts:
        src = open(f).read(); assert src.count(old) == 1, name     # exactly the one place the bug went back
        shutil.copy(f, f + ".bak"); open(f, "w").write(src.replace(old, new, 1))
        _drop_cache(f)
        r = subprocess.run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-k", sel],
                           capture_output=True, text=True, env=ENV)
        shutil.move(f + ".bak", f)
        _drop_cache(f)
        # pytest exits 5 when the selector matched no test: nothing ran, so nothing was caught
        caught = r.returncode not in (0, 5)
        bad += not caught
        print(("CAUGHT " if caught else "MISSED ") + name, "|", r.stdout.strip().splitlines()[-1])
    return bad


if __name__ == "__main__":
    sys.exit(main())
