"""Check the checker: put each VBA bug back and prove its test goes red.

Run from origination-cube/: python tools/mutation_check.py. Exits non-zero
if any mutation survives."""
import subprocess, shutil, sys
E="src/origination_cube/engine.py"; C="src/origination_cube/config.py"; B="src/origination_cube/book.py"
S="src/origination_cube/stats.py"; P="src/origination_cube/perm.py"
muts = [
 ("1 blank->zero",       E, 'if p is BLANK:\n        return None, "blank"', 'if p is BLANK:\n        return 0.0, None', "test_finding_1"),
 ("2 empty->index 0",    E, 'if rate is None or base is None or base == 0:', 'if base is None or base == 0:\n        return None\n    if rate is None:\n        rate = 0.0\n    if False:', "test_finding_2"),
 ("4 text->0 on top",    E, '                if why_t or why_d:', '                if why_t and not why_d and m.mode == "sumnum":\n                    vals.append((0.0, d)); continue\n                if why_t or why_d:', "test_finding_4"),
 ("8 threshold default", C, '    absent = [k for k in BENCHMARK_KEYS if k not in node]', '    node = {"min_units": 30, "worse_at": 1.25, "better_at": 0.8, "confidence": 0.95, "power": 0.8, **node}\n    absent = [k for k in BENCHMARK_KEYS if k not in node]', "test_finding_8"),
 ("tie-out disabled",    E, '        if not _close(got, want, scale):', '        if False:', "test_the_tie_out"),
 ("unknown keys ignored",C, '        if k not in allowed:', '        if False:', "misspelled"),
 ("judgment pre-chosen", "src/origination_cube/control.py",
  'value=None if s.judgment or rec is None else rec.shown)',
  'value=(rec or s.options[0]).shown)', "waits_for_every_judgment"),
 ("outcome cut by",      E, '    tops = {m.value if m.mode == "sumnum" else m.flag for m in measures if m.is_rate}',
  '    tops = set()', "outcome"),
 ("unconfirmed columns run", C, '        if raw.get("columns_confirmed") is not True:',
  '        if False:', "confirms_it"),
 ("memory ignored", "src/origination_cube/meanings.py",
  '        if hit and hit.get("means") in cat:', '        if False:', "remembered_and_outranks"),
 ("forget forgets nothing", "src/origination_cube/memory.py",
  '        if mem["columns"].pop(n, None) is not None:', '        if mem["columns"].get(n) is None:', "forget_by_name"),
 ("RANR read as a loss", E, '                s.excess = (s.num - top * s.den) if hi == "worse" else (top * s.den - s.num)',
  '                s.excess = s.num - top * s.den', "ranr_is_revenue"),
 ("loss floor ignored",  E, '    if events is not None and higher_is == "worse" and events < min_events:',
  '    if False:', "too_few_losses"),
 ("no allowance for many tests", E, '    if how == "none" or m == 0:', '    if True:', "allowance"),
 ("judged-against ignored", E, '                if bench.compare_to == "peers":', '                if False:', "judged_against"),
 ("materiality ignored", E, '                s.material = s.excess > 0 and s.excess >= mat', '                s.material = s.excess > 0',
  "materiality_as"),
 ("loan age ignored",    E, '    if not config.min_age_months and not config.window_months:', '    if True:',
  "loan_age_keeps"),
 ("key optional again",  E, '    if config.key not in have:', '    if False:', "missing_key"),
 ("reading on whole-book multiple", E, '            s.reading_topline = reading_of(s.vs_rest, s.units, judge, floor, s.p_book, **kw)',
  '            s.reading_topline = reading_of(s.vs_topline, s.units, judge, floor, s.p_book, **kw)', "big_pocket"),
 # 25 Sep 2026: the third layer, losses against revenue, and the second walk's defects
 ("split not pooled",    E, '        if strata:', '        if False:', "planted_revolving"),
 ("dollar outcome pooled as loan odds", E, '            if m.mode == "flagwt" and m.per == EACH_LOAN:',
  '            if m.mode == "flagwt":', "planted_revolving"),
 ("halves at the book's median", E, '        med = {k: statistics.median(v) for k, v in groups.items()}',
  '        med = {k: statistics.median([x for g in groups.values() for x in g]) for k in groups}', "own_median"),
 ("copied book runs old extract", B, '    if extract is not None:', '    if False:', "copied_workbook"),
 ("forget re-learned",   B, '    if dropped:\n        # a Forget', '    if False:\n        # a Forget', "learned_tab_prunes"),
 ("yes kept over new columns", B, 'and not new_cols else None', ' else None', "new_column_takes"),
 ("set up deletes results", B, '            if t in INPUT_TABS or t in HELPERS:', '            if True:', "keeps_the_last_results"),
 ("open workbook not checked", B, '    if not _writable(book):', '    if False:', "open_in_excel"),
 ("edges read as one number", B, 'abs(e) >= 100000', 'abs(e) >= 1e30', "one_number"),
 ("edge range unchecked", B, '        if bad:', '        if False:', "outside_the_columns"),
 ("boxes by 1.00x again", B, '    return "more" if idx >= hi else "less" if idx <= lo else "same"',
  '    return "more" if idx > 1 else "less"', "boxes_follow"),
 ("split ignores the minimums", E, '            if thin or few:', '            if sh.rate is None or sl.rate is None:',
  "under_the_minimum"),
 ("three-way not built", E, '                three_way.append(three)', '                pass', "three_way_pockets"),
 ("any column splits", B, '            if cat[code].cut in ("band", "dimension"):', '            if True:', "cant_split"),
 ("dollar line on every rate", E, '        elif m.name == "gco_rate":', '        elif True:', "gco_only"),
 ("forget lasts one run", B, '    if forgotten and "Columns" in wb.sheetnames:', '    if False:', "forget_holds"),
 ("workbook taken as extract", B, '    if extract.name.endswith(" - Origination Cube.xlsx"):', '    if False:',
  "own_extract"),
 ("heat maps colour untested", B, 's.vs_topline if s.reading_topline not in untested', 's.vs_topline if True',
  "leave_out_pockets"),
 ("RANR gap reads or more", B, """else '0.00"x or less"')""", """else '0.00"x or more"')""", "ranr_is_marked"),
 ("band width ignored",  B, '    far = _band_widths(raw, about.get("_widths") or {}, cfg, table, about.get("_edge_cells"))', '    far = []', "every_20"),
 ("suggestion not worked out", B, '        if about.get("_suggest"):', '        if False:', "suggested_answers"),
 ("edges not remembered", "src/origination_cube/memory.py", '        if text:\n            e["edges"] = text',
  '        if False:\n            e["edges"] = text', "every_20"),
 ("dollars against the book", B, '            parent = g.cells[(bl, engine.ALL)] if peers else res.total',
  '            parent = res.total', "dollars_agree"),
 ("untested pockets boxed", B, '            untested = {gflag, rflag} & {engine.THIN, engine.FEW}',
  '            untested = set()', "dollars_agree"),
 ("three-way without its caveat", B, '        note = (lambda g: _three_way_note(res, g)) if res.config.split[1] == "own_median" else None',
  '        note = None', "holds_fixed"),
 ("luck line at the catch rate", B, '                x = stats.smallest_gap_for(ln, s.units, b.confidence, 0.5)',
  '                x = stats.smallest_gap_for(ln, s.units, b.confidence, b.power)', "luck_alone"),
 ("bands say up to", E, "        first = f(math.floor(lo / step) * step) if lo is not None and lo < edges[0] else None",
  "        first = None", "bands_read_as_ranges"),
 ("grids lose the data range", E, "        labels = band_labels(edges, min(seen), max(seen)) if seen else band_labels(edges)",
  "        labels = band_labels(edges)", "boxes_follow"),
 ("in use refuses a number", "src/origination_cube/control.py",
  '        lookup = (f"IFERROR(MATCH({H}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0),"\n                  f"MATCH({H}&\\"|\\"&IFERROR(VALUE({C}),{C}),{OPTIONS_SHEET}!$H:$H,0))")',
  '        lookup = f"MATCH({H}&\\"|\\"&{C},{OPTIONS_SHEET}!$A:$A,0)"', "number_the_run_takes"),
 ("rest rate from the book", B, '_rest_rate(gs, pg), gidx,', '_rest_rate(gs, res.total.rates["gco_rate"]), gidx,', "boxes_follow"),
 ("luck side coloured", B, '"gside": None if untested or luck["loss"] else gside,', '"gside": None if untested else gside,',
  "luck_gap_keeps"),
 ("negative comparison divided plainly", "src/origination_cube/stats.py",
  '    return ra / rb if rb > 0 else 1 + (ra - rb) / abs(rb)', '    return ra / rb', "negative_comparison"),
 ("blue counts rows", B, '    small = len(set(blue))', '    small = len(blue)', "too_small_to_test_are_pointed"),
 ("fallback called worked out", B, '        lines_ = [k for k in ("worse_at", "better_at") if k in sug and k not in fb]',
  '        lines_ = [k for k in ("worse_at", "better_at") if k in sug]', "nothing_to_work_from"),
 ("category limits ignored", B, '            method[key] = int(got)', '            pass', "category_limits"),
 ("guesses ignore the limits", "src/origination_cube/meanings.py",
  '            elif f.numeric and len(set(f.numbers)) > few_values:', '            elif f.numeric and len(set(f.numbers)) > 12:',
  "category_limits"),
 ("revenue by the loss lines", E, '                judge, kw["luck_only"] = revenue_bench(bench)', '                judge = bench',
  "same_on_both_tabs or follows_the_revenue_setting"),
 ("three-way red on unheld rows", B,
  """    red = 'AND($Q5="worse",LEFT($S5,3)<>"no:")' if note_of else '$Q5="worse"'""",
  """    red = '$Q5="worse"'""", "three_way_rows_say"),
 ("luck not marked", B, '            luck = {"loss": "loss" in maybe and gflag not in (engine.THIN, engine.FEW),',
  '            luck = {"loss": False,', "luck_gap_keeps"),
 ("edges leak between workbooks", B, '            if c not in kept["columns"] and cat[code].cut == "band" else None',
  '            if cat[code].cut == "band" else None',
  "edges_stay_out"),
 ("last run not shown", B, '        _last_run_used(wb[control.SHEET], res)', '        pass', "last_run_used"),
 ("split luck without the allowance", E, '        if bench is not None:\n            keys = [k for k, got in grid.split_compare.items()',
  '        if False:\n            keys = [k for k, got in grid.split_compare.items()', "carry_the_allowance"),
 ("revenue line one number again", E, '    if luck_only and tested:', '    if False:',
  "planted_pocket_is_not or follows_the_revenue_setting"),
 ("fallback called worked out", B, '            res.suggest_fallback = fallback', '            pass', "nothing_to_work_from"),
 ("split luck shaded", B, '                return got[0] if got[1] is not None and got[1] < 1 - conf else f"({got[0]:.2f}x)"',
  '                return got[0]', "bracketed"),
 ("small material pockets not pointed out", B, '    if small:\n        rows_said', '    if False:\n        rows_said',
  "too_small_to_test"),
 ("start here left stale", B, 'else f"{stamp}: {lines[0]}")', 'else stamp)', "start_here"),
 # NEXT-GOAL 3.15: the pre-spec
 ("pre-spec edited but read as committed", "src/origination_cube/prespec.py",
  '        dirty = bool(status.stdout.strip())', '        dirty = False', "dirty"),
 ("holdout ends left out", "src/origination_cube/prespec.py",
  '        return self.start <= d <= self.end', '        return self.start < d < self.end', "holdout_touch"),
 # OC-34: the add-ons
 ("run on while an add-on is missing", "src/origination_cube/launcher.py",
  '"run": _on(ready)', '"run": "normal"', "set_up_and_run_wait"),
 ("install ok on pip's word", "src/origination_cube/deps.py",
  '    return not still, out', '    return rc == 0, out', "only_ok_when_the_check_after"),
 ("first install unseen until restart", "src/origination_cube/deps.py",
  '            site.addsitedir(user)', '            pass', "seen_without_a_restart"),
 # fix 3.8: the Look tab
 ("look spreads over the code", "src/origination_cube/look.py", '    values = sorted(x for x in nums if x != code)',
  '    values = sorted(nums)', "test_look"),
 # 25 Sep 2026: the tests of docs/statistics.md, rulings OC-34 to OC-37
 ("share of loans unpooled again", S, '    return math.sqrt(max(pbar * (1 - pbar), 0.0) * (1 / n1 + 1 / n2))',
  '    p1, p2 = x1 / n1, x2 / n2\n    return math.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)', "a1_ or family_is_the_inner"),
 ("Fisher one-sided", S, '    return min(1.0, math.fsum(math.exp(v) for v in logs if v <= cut))',
  '    return min(1.0, math.fsum(math.exp(v) for v in logs[k - lo:]))', "fisher"),
 ("shuffle p without the +1", P, '        return (self.hits + 1) / (self.shuffles + 1)', '        return self.hits / self.shuffles',
  "plus_one"),
 ("shuffled across the band", P, '                order = pi if codes is None else pi[np.argsort(codes[pi], kind="stable")]',
  '                order = pi if codes is None else pi[np.argsort(codes, kind="stable")]', "within"),
 ("family counts the totals", E, '    pockets = [k for k in cells if k[0] != ALL and k[1] != ALL]',
  '    pockets = [k for k in cells if k != (ALL, ALL)]', "family_is_the_inner"),
 ("CMH subtracts a half again", S, '    chi = num * num / var', '    chi = (max(abs(num) - 0.5, 0.0)) ** 2 / var',
  "cmh or a5_to_a8"),
 ("fewest loans refuses again", E, '    if not tested and units < min_units:', '    if units < min_units:', "walk_6"),
 ("z test below the floor", E, '    if n1 >= floor:', '    if True:', "walk_6"),
 ("shuffle ties dropped", P, '        self.hits += (~(np.abs(g) < self.thr)).sum(axis=0)',
  '        self.hits += (np.abs(g) > np.abs(self.g)).sum(axis=0)', "exact_tie"),
 # NEXT-GOAL 3.13 and 3.14: dated outcomes and the window (tests/test_dates.py, tests/test_book_dates.py)
 ("window ignored", E, '    if config.window_months:\n        return _window(', '    if False:\n        return _window(',
  "the_window_counts"),
 ("bad after the window kept bad", E, '        if bad is True and k >= n:', '        if False:', "the_window_counts"),
 ("window edge a month late", E, '        if bad is True and k >= n:', '        if bad is True and k > n:',
  "anniversary"),
 ("young loans kept in the window", E, '        if age < n:\n            left[young] += 1',
  '        if False:\n            left[young] += 1', "anniversary"),
 ("outcome date on a good loan ignored", E, '        elif bad is False and not is_blank(raw_out):',
  '        elif False:', "date_problem"),
 ("undated bad loan assumed in the window", E,
  '            if not isinstance(od, _date):\n                left[BAD_NO_DATE] += 1\n                continue',
  '            if not isinstance(od, _date):\n                od = d', "date_problem"),
 ("seasoned counts every loan", E, '        if age >= rep.seasoned_at:', '        if True:', "seasoned"),
 ("latest is the earliest", E, '        return max(seen), "the latest', '        return min(seen), "the latest',
  "as_of_latest"),
 ("dates read one way by default", E, '    if det.ambiguous:', '    if False:', "read_two_ways"),
 ("window without an outcome date", C, '    if n > 0 and not out_date:', '    if False:', "refused_without_its_dates"),
 ("outcome date with no window said", C, '        if out_date:\n            problems.append(f"an outcome date',
  '        if False:\n            problems.append(f"an outcome date', "needs_the_window_said"),
 ("age filter and window both", C, '    if n > 0 and age > 0:', '    if False:', "age_filter_and_the_window"),
 ("bad date YAML raises", C, '    except ValueError as exc:\n        # an unquoted',
  '    except KeyError as exc:\n        # an unquoted', "not_a_real_day"),
 ("two origination dates", C, '        if len(hits) > 1:\n            # one column each',
  '        if False:\n            # one column each', "one_column_per_date_role"),
 ("window not asked for on Control", B, '    if window is None and marked["outcome_date"]:', '    if False:',
  "asked_for_when_they_matter"),
 ("as-of not asked for on Control", B, '    elif (window or age) and not marked["as_of_date"]:', '    elif False:',
  "asked_for_when_they_matter"),
 ("cube init skips the window", "src/origination_cube/profile.py",
  '    if any(sg.means == "outcome_date" for sg in sugg.values()):', '    if False:', "asks_for_the_window"),
 ("an outcome date's blanks flagged", "src/origination_cube/meanings.py",
  '        if c in sugg and sugg[c].means == "outcome_date":\n            continue',
  '        if False:\n            continue', "asks_for_the_window"),
 ("every when-needed call counted", B, '    if not s.needed_when:\n        return True',
  '    if True:\n        return True', "asked_for_when_they_matter"),
 ("typed as-of date refused", "src/origination_cube/control.py", '            elif s.is_date:', '            elif False:',
  "typed_and_is_read"),
 ("when-needed settings always refused", "src/origination_cube/control.py",
  '            if s.needed_when:\n                continue', '            if False:\n                continue',
  "waits_for_every_judgment"),
 # NEXT-GOAL 3.9 to 3.11: a new column, its period and its meaning (tests/test_derived.py, tests/test_book_dates.py)
 ("new column not made", E, '    table, derived = derive(config, table, warnings)', '    derived = []',
  "one_column_over_another"),
 ("zero bottom not blank", E, '            elif b == 0:', '            elif False:', "zero_or_blank_bottom"),
 ("blank new value read as zero", E, '            r[d.name] = v', '            r[d.name] = 0.0 if v is None else v',
  "zero_or_blank_bottom"),
 ("missing rule skipped on the bottom", E, '        rt, rb = rules.get(d.top), rules.get(d.bottom)',
  '        rt, rb = rules.get(d.top), None', "missing_rule_on_the_bottom"),
 ("new column shadows an extract column", E, '        if d.name in table.columns:\n            raise DataRefused',
  '        if False:\n            raise DataRefused', "named_like_a_column"),
 ("periods never compared", E, '        if pt and pb and pt != pb:', '        if False:', "periods_that_disagree"),
 ("period on a category", C, '            elif means not in AMOUNT_MEANINGS:', '            elif False:',
  "period_is_for_an_amount"),
 ("definition dropped", C, '                definitions[str(col)] = " ".join(d.split())', '                pass',
  "period_is_for_an_amount"),
 ("stale new column runs", B, '        elif made[1] != now:', '        elif False:', "made_on_control"),
 ("new column run before set up", B, '        elif made is None:\n            problems.append',
  '        elif made is None and False:\n            problems.append', "made_on_control"),
 ("Look loses the new column at Run", B, '        look.refresh(book, res.table or table, res.config.split',
  '        look.refresh(book, table, res.config.split', "made_on_control"),
 ("period on Columns not recorded", B, '                entry["period"] = PERIOD_OPTIONS[str(per).strip()]',
  '                pass', "periods_and_meanings"),
 ("ratio plant missing", "src/origination_cube/synth.py",
  '            if not bad or rng.random() < _odds(ratio) / top:', '            if True:', "plants_the_ratio"),
 ("bad dates after the as-of date", "src/origination_cube/synth.py", '                if days <= days_on_book:',
  '                if True:', "outcome_date_on_bad_loans"),
]
bad = 0
for name, f, old, new, sel in muts:
    src = open(f).read(); assert src.count(old) == 1, name     # exactly the one place the bug went back
    shutil.copy(f, f + ".bak"); open(f, "w").write(src.replace(old, new, 1))
    r = subprocess.run([sys.executable, "-m", "pytest", "-q", "-k", sel], capture_output=True, text=True)
    shutil.move(f + ".bak", f)
    # pytest exits 5 when the selector matched no test: nothing ran, so nothing was caught
    caught = r.returncode not in (0, 5)
    bad += not caught
    print(("CAUGHT " if caught else "MISSED ") + name, "|", r.stdout.strip().splitlines()[-1])
sys.exit(bad)
