// Generated by scripts/build-browser.js. Do not edit directly.
// This classic script bundle lets index.html run from file:// without ES module loading.
(() => {
'use strict';

// src/workflows.js
const TASK_AUDIENCES = {
  internal: 'Internal',
  client: 'Client-facing'
};

const workflows = {
  newTaxClientOnboarding: {
    name: 'New tax client onboarding',
    description: 'Collect authorization, prior-year details, entity information, and engagement documents.',
    questions: [
      { id: 'hasPriorYearReturns', label: 'Does the client have prior-year tax returns to provide?', type: 'yesNo' },
      { id: 'hasIrsNotices', label: 'Does the client have IRS or state notices?', type: 'yesNo' },
      { id: 'multiStateFiling', label: 'Will the client need multi-state filing review?', type: 'yesNo' },
      { id: 'businessOwner', label: 'Does the client own a business or rental entity?', type: 'yesNo' },
      { id: 'needsBookkeepingSetup', label: 'Does the client need bookkeeping setup?', type: 'yesNo' }
    ],
    tasks: [
      { templateId: 'onboarding-send-welcome-email', title: 'Send welcome email and secure portal invitation', daysBeforeDue: 21, category: 'Kickoff', audience: 'client' },
      { templateId: 'onboarding-request-engagement-letter', title: 'Request signed engagement letter', daysBeforeDue: 20, category: 'Authorization', audience: 'client' },
      { templateId: 'onboarding-gather-intake-questionnaire', title: 'Gather client intake questionnaire and contact details', daysBeforeDue: 16, category: 'Client information', audience: 'client' },
      { templateId: 'onboarding-confirm-filing-details', title: 'Confirm filing status, dependents, entities, and state obligations', daysBeforeDue: 14, category: 'Review', audience: 'internal' },
      { templateId: 'onboarding-set-up-client-folder', title: 'Set up client folder and document checklist', daysBeforeDue: 12, category: 'Internal setup', audience: 'internal' },
      { templateId: 'onboarding-schedule-kickoff-call', title: 'Schedule kickoff or discovery call', daysBeforeDue: 10, category: 'Kickoff', audience: 'client' },
      { templateId: 'onboarding-review-open-questions', title: 'Review open questions and assign next steps', daysBeforeDue: 7, category: 'Review', audience: 'internal' },
      {
        templateId: 'onboarding-request-prior-year-returns',
        title: 'Request prior-year tax returns and carryforward details',
        daysBeforeDue: 18,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'hasPriorYearReturns', equals: 'yes' }
      },
      {
        templateId: 'onboarding-request-tax-notices',
        title: 'Request copies of IRS or state notices and response deadlines',
        daysBeforeDue: 17,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'hasIrsNotices', equals: 'yes' }
      },
      {
        templateId: 'onboarding-map-state-filing-requirements',
        title: 'Map resident and nonresident state filing requirements',
        daysBeforeDue: 13,
        category: 'Review',
        audience: 'internal',
        condition: { questionId: 'multiStateFiling', equals: 'yes' }
      },
      {
        templateId: 'onboarding-request-entity-documents',
        title: 'Request entity documents, ownership details, and accounting access',
        daysBeforeDue: 13,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'businessOwner', equals: 'yes' }
      },
      {
        templateId: 'onboarding-create-bookkeeping-setup-plan',
        title: 'Create bookkeeping setup plan and chart-of-accounts checklist',
        daysBeforeDue: 11,
        category: 'Internal setup',
        audience: 'internal',
        condition: { questionId: 'needsBookkeepingSetup', equals: 'yes' }
      }
    ]
  },
  monthlyBookkeeping: {
    name: 'Monthly bookkeeping',
    description: 'Close the month with reconciliations, reviews, reports, and client follow-up.',
    questions: [
      { id: 'usesPayroll', label: 'Did the client run payroll this month?', type: 'yesNo' },
      { id: 'hasLoanActivity', label: 'Was there loan or financing activity?', type: 'yesNo' },
      { id: 'inventoryActivity', label: 'Did inventory change materially?', type: 'yesNo' },
      { id: 'salesTaxFilingDue', label: 'Is a sales tax filing due?', type: 'yesNo' },
      { id: 'unclearedTransactions', label: 'Are there uncleared or uncategorized transactions?', type: 'yesNo' }
    ],
    tasks: [
      { templateId: 'monthly-request-bank-statements', title: 'Request bank, credit card, and loan statements', daysBeforeDue: 10, category: 'Document requests', audience: 'client' },
      { templateId: 'monthly-import-transactions', title: 'Import transactions and refresh bank feeds', daysBeforeDue: 9, category: 'Data entry', audience: 'internal' },
      { templateId: 'monthly-categorize-transactions', title: 'Categorize income and expenses', daysBeforeDue: 7, category: 'Data entry', audience: 'internal' },
      { templateId: 'monthly-reconcile-bank-credit-cards', title: 'Reconcile bank and credit card accounts', daysBeforeDue: 5, category: 'Reconciliation', audience: 'internal' },
      { templateId: 'monthly-review-ar-ap', title: 'Review accounts receivable and accounts payable', daysBeforeDue: 4, category: 'Review', audience: 'internal' },
      { templateId: 'monthly-post-adjusting-entries', title: 'Post depreciation, accruals, and recurring journal entries', daysBeforeDue: 3, category: 'Adjustments', audience: 'internal' },
      { templateId: 'monthly-prepare-financial-statements', title: 'Prepare financial statements and management notes', daysBeforeDue: 2, category: 'Reporting', audience: 'internal' },
      { templateId: 'monthly-send-close-package', title: 'Send monthly close package to client', daysBeforeDue: 0, category: 'Reporting', audience: 'client' },
      {
        templateId: 'monthly-request-payroll-reports',
        title: 'Request payroll reports and tie wages to payroll tax liabilities',
        daysBeforeDue: 6,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'usesPayroll', equals: 'yes' }
      },
      {
        templateId: 'monthly-review-loan-activity',
        title: 'Review loan statements, interest, principal, and new financing entries',
        daysBeforeDue: 5,
        category: 'Reconciliation',
        audience: 'internal',
        condition: { questionId: 'hasLoanActivity', equals: 'yes' }
      },
      {
        templateId: 'monthly-request-inventory-report',
        title: 'Request inventory count or valuation report',
        daysBeforeDue: 5,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'inventoryActivity', equals: 'yes' }
      },
      {
        templateId: 'monthly-prepare-sales-tax-support',
        title: 'Prepare sales tax reconciliation and filing support',
        daysBeforeDue: 3,
        category: 'Compliance',
        audience: 'internal',
        condition: { questionId: 'salesTaxFilingDue', equals: 'yes' }
      },
      {
        templateId: 'monthly-send-transaction-questions',
        title: 'Send transaction question list to client',
        daysBeforeDue: 4,
        category: 'Client follow-up',
        audience: 'client',
        condition: { questionId: 'unclearedTransactions', equals: 'yes' }
      }
    ]
  },
  yearEndCleanup: {
    name: 'Year-end cleanup',
    description: 'Prepare books for tax-ready year-end review and reporting.',
    questions: [
      { id: 'newFixedAssets', label: 'Were fixed assets purchased or disposed?', type: 'yesNo' },
      { id: 'hasPayroll', label: 'Did the client have payroll during the year?', type: 'yesNo' },
      { id: 'needs1099Review', label: 'Does the client need 1099 vendor review?', type: 'yesNo' },
      { id: 'ownerContributions', label: 'Were there owner contributions or distributions?', type: 'yesNo' },
      { id: 'openSuspenseItems', label: 'Are there suspense or uncategorized items?', type: 'yesNo' }
    ],
    tasks: [
      { templateId: 'year-end-lock-periods-backup-file', title: 'Lock prior reviewed periods and backup accounting file', daysBeforeDue: 30, category: 'Preparation', audience: 'internal' },
      { templateId: 'year-end-reconcile-cash-credit-loans', title: 'Reconcile all cash, credit card, and loan accounts', daysBeforeDue: 25, category: 'Reconciliation', audience: 'internal' },
      { templateId: 'year-end-review-suspense-accounts', title: 'Review uncategorized and suspense accounts', daysBeforeDue: 20, category: 'Cleanup', audience: 'internal' },
      { templateId: 'year-end-prepare-adjusting-entries', title: 'Prepare adjusting journal entries', daysBeforeDue: 7, category: 'Adjustments', audience: 'internal' },
      { templateId: 'year-end-deliver-tax-ready-trial-balance', title: 'Deliver tax-ready trial balance and cleanup notes', daysBeforeDue: 0, category: 'Reporting', audience: 'client' },
      {
        templateId: 'year-end-request-asset-documents',
        title: 'Request asset purchase invoices and disposal documentation',
        daysBeforeDue: 18,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'newFixedAssets', equals: 'yes' }
      },
      {
        templateId: 'year-end-update-fixed-assets',
        title: 'Update fixed asset register and depreciation entries',
        daysBeforeDue: 16,
        category: 'Adjustments',
        audience: 'internal',
        condition: { questionId: 'newFixedAssets', equals: 'yes' }
      },
      {
        templateId: 'year-end-request-annual-payroll-reports',
        title: 'Request annual payroll reports and reconcile wages to payroll tax filings',
        daysBeforeDue: 12,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'hasPayroll', equals: 'yes' }
      },
      {
        templateId: 'year-end-review-1099-vendor-list',
        title: 'Request W-9s and confirm 1099 vendor payment totals',
        daysBeforeDue: 10,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'needs1099Review', equals: 'yes' }
      },
      {
        templateId: 'year-end-reconcile-owner-equity',
        title: 'Reconcile owner contributions, draws, and equity rollforward',
        daysBeforeDue: 9,
        category: 'Review',
        audience: 'internal',
        condition: { questionId: 'ownerContributions', equals: 'yes' }
      },
      {
        templateId: 'year-end-send-suspense-questions',
        title: 'Send suspense item question list to client',
        daysBeforeDue: 8,
        category: 'Client follow-up',
        audience: 'client',
        condition: { questionId: 'openSuspenseItems', equals: 'yes' }
      }
    ]
  },
  rentalPropertyTaxPrep: {
    name: 'Rental property tax prep',
    description: 'Collect rental income, expense, asset, and ownership details for tax preparation.',
    questions: [
      { id: 'purchasedThisYear', label: 'Was the property purchased this year?', type: 'yesNo' },
      { id: 'soldThisYear', label: 'Was the property sold this year?', type: 'yesNo' },
      { id: 'majorImprovements', label: 'Were there major improvements?', type: 'yesNo' },
      { id: 'personalUseDays', label: 'Were there personal-use days?', type: 'yesNo' },
      { id: 'shortTermRentalActivity', label: 'Was there short-term rental activity?', type: 'yesNo' },
      { id: 'outOfStateProperty', label: 'Is the property out of state?', type: 'yesNo' },
      { id: 'propertyManager', label: 'Was a property manager used?', type: 'yesNo' },
      { id: 'refinanceOrNewMortgage', label: 'Was there a refinance or new mortgage?', type: 'yesNo' },
      { id: 'casualtyLossOrInsuranceClaim', label: 'Was there a casualty loss or insurance claim?', type: 'yesNo' }
    ],
    tasks: [
      { templateId: 'rental-request-rent-roll', title: 'Request rent roll and annual income summary', daysBeforeDue: 18, category: 'Document requests', audience: 'client' },
      { templateId: 'rental-collect-mortgage-tax-statements', title: 'Collect mortgage interest and property tax statements', daysBeforeDue: 16, category: 'Document requests', audience: 'client' },
      { templateId: 'rental-gather-expense-documents', title: 'Gather repair, maintenance, utility, and insurance expenses', daysBeforeDue: 14, category: 'Document requests', audience: 'client' },
      { templateId: 'rental-identify-improvements-repairs', title: 'Identify improvements versus repairs', daysBeforeDue: 12, category: 'Review', audience: 'internal' },
      { templateId: 'rental-confirm-personal-use-days', title: 'Confirm personal-use days and rental-use days', daysBeforeDue: 10, category: 'Client follow-up', audience: 'client' },
      { templateId: 'rental-review-mileage-travel-management', title: 'Review mileage, travel, and management fees', daysBeforeDue: 8, category: 'Review', audience: 'internal' },
      { templateId: 'rental-update-depreciation-schedule', title: 'Update depreciation schedule for new assets or disposals', daysBeforeDue: 5, category: 'Adjustments', audience: 'internal' },
      { templateId: 'rental-prepare-tax-summary', title: 'Prepare rental property tax summary for review', daysBeforeDue: 0, category: 'Reporting', audience: 'internal' },
      {
        templateId: 'rental-collect-purchase-closing-statement',
        title: 'Collect closing statement and purchase allocation details',
        daysBeforeDue: 15,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'purchasedThisYear', equals: 'yes' }
      },
      {
        templateId: 'rental-collect-sale-closing-statement',
        title: 'Collect sale closing statement and calculate rental property disposition details',
        daysBeforeDue: 15,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'soldThisYear', equals: 'yes' }
      },
      {
        templateId: 'rental-request-improvement-invoices',
        title: 'Request invoices and placed-in-service dates for major improvements',
        daysBeforeDue: 13,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'majorImprovements', equals: 'yes' }
      },
      {
        templateId: 'rental-review-personal-use-days',
        title: 'Document personal-use days and allocate mixed-use expenses',
        daysBeforeDue: 9,
        category: 'Review',
        audience: 'internal',
        condition: { questionId: 'personalUseDays', equals: 'yes' }
      },
      {
        templateId: 'rental-review-short-term-rental-activity',
        title: 'Review short-term rental days, services provided, and occupancy tax details',
        daysBeforeDue: 9,
        category: 'Compliance',
        audience: 'internal',
        condition: { questionId: 'shortTermRentalActivity', equals: 'yes' }
      },
      {
        templateId: 'rental-confirm-out-of-state-filing',
        title: 'Confirm nonresident state filing requirements for out-of-state property',
        daysBeforeDue: 8,
        category: 'Compliance',
        audience: 'internal',
        condition: { questionId: 'outOfStateProperty', equals: 'yes' }
      },
      {
        templateId: 'rental-request-property-manager-statement',
        title: 'Request property manager annual statement and fee detail',
        daysBeforeDue: 7,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'propertyManager', equals: 'yes' }
      },
      {
        templateId: 'rental-collect-refinance-mortgage-documents',
        title: 'Collect refinance or new mortgage closing costs and loan terms',
        daysBeforeDue: 6,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'refinanceOrNewMortgage', equals: 'yes' }
      },
      {
        templateId: 'rental-gather-casualty-insurance-documents',
        title: 'Gather casualty loss records, insurance claim documents, and reimbursements',
        daysBeforeDue: 6,
        category: 'Document requests',
        audience: 'client',
        condition: { questionId: 'casualtyLossOrInsuranceClaim', equals: 'yes' }
      }
    ]
  }
};

function calculateSuggestedDate(dueDateValue, daysBeforeDue) {
  const dueDate = new Date(`${dueDateValue}T12:00:00`);

  if (Number.isNaN(dueDate.getTime())) {
    throw new Error('A valid due date is required.');
  }

  const suggestedDate = new Date(dueDate);
  suggestedDate.setDate(suggestedDate.getDate() - daysBeforeDue);
  return suggestedDate.toISOString().slice(0, 10);
}

function shouldIncludeTask(task, answers = {}) {
  if (!task.condition) {
    return true;
  }

  return answers[task.condition.questionId] === task.condition.equals;
}

function getWorkflowQuestions(workflowKey) {
  return workflows[workflowKey]?.questions ?? [];
}

function cleanClientName(clientName) {
  const cleanedName = clientName.trim();

  if (!cleanedName) {
    throw new Error('Client name is required.');
  }

  return cleanedName;
}

function normalizeIntakeAnswers(workflow, answers = {}) {
  return (workflow.questions ?? []).reduce((savedAnswers, question) => {
    savedAnswers[question.id] = answers[question.id] ?? '';
    return savedAnswers;
  }, {});
}

function createId(prefix) {
  if (globalThis.crypto?.randomUUID) {
    return `${prefix}-${globalThis.crypto.randomUUID()}`;
  }

  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function buildTasks({ workflowKey, dueDate, intakeAnswers, existingTasks = [] }) {
  const workflow = workflows[workflowKey];
  const existingTasksByTemplateId = new Map(
    existingTasks.filter((task) => task.templateId).map((task) => [task.templateId, task])
  );
  const legacyExistingTasksByTitle = new Map(existingTasks.map((task) => [task.title, task]));

  return workflow.tasks.filter((task) => shouldIncludeTask(task, intakeAnswers)).map((task, index) => {
    const existingTask = existingTasksByTemplateId.get(task.templateId) ?? legacyExistingTasksByTitle.get(task.title);

    return {
      id: existingTask?.id ?? createId(`${workflowKey}-${index}`),
      templateId: task.templateId,
      title: task.title,
      category: task.category,
      audience: task.audience,
      audienceLabel: TASK_AUDIENCES[task.audience],
      suggestedDate: calculateSuggestedDate(dueDate, task.daysBeforeDue),
      completed: existingTask?.completed ?? false,
      notes: existingTask?.notes ?? ''
    };
  });
}

function buildChecklist({ clientName, dueDate, workflowKey, answers = {} }) {
  const workflow = workflows[workflowKey];

  if (!workflow) {
    throw new Error('A valid workflow is required.');
  }

  const intakeAnswers = normalizeIntakeAnswers(workflow, answers);

  return {
    id: createId('checklist'),
    clientName: cleanClientName(clientName),
    dueDate,
    workflowKey,
    workflowName: workflow.name,
    intakeAnswers,
    createdAt: new Date().toISOString(),
    tasks: buildTasks({ workflowKey, dueDate, intakeAnswers })
  };
}

function regenerateChecklist(checklist, { clientName, dueDate, answers = {} }) {
  const workflow = workflows[checklist.workflowKey];

  if (!workflow) {
    throw new Error('A valid workflow is required.');
  }

  const intakeAnswers = normalizeIntakeAnswers(workflow, answers);

  return {
    ...checklist,
    clientName: cleanClientName(clientName),
    dueDate,
    intakeAnswers,
    updatedAt: new Date().toISOString(),
    tasks: buildTasks({
      workflowKey: checklist.workflowKey,
      dueDate,
      intakeAnswers,
      existingTasks: checklist.tasks
    })
  };
}

function duplicateChecklist(checklist) {
  return {
    ...checklist,
    id: createId('checklist'),
    clientName: `${checklist.clientName} (Copy)`,
    createdAt: new Date().toISOString(),
    updatedAt: undefined,
    tasks: checklist.tasks.map((task) => ({
      ...task,
      id: createId(`${checklist.workflowKey}-duplicate`)
    }))
  };
}


// src/outputs.js

function getClientFacingTasks(tasks = []) {
  return tasks.filter((task) => task.audience === 'client');
}

function groupTasksByCategory(tasks = []) {
  const groups = [];
  const groupIndexes = new Map();

  tasks.forEach((task) => {
    const category = task.category || 'General';

    if (!groupIndexes.has(category)) {
      groupIndexes.set(category, groups.length);
      groups.push({ category, tasks: [] });
    }

    groups[groupIndexes.get(category)].tasks.push(task);
  });

  return groups;
}

function formatOutputDate(dateValue) {
  return new Intl.DateTimeFormat('en', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC'
  }).format(new Date(`${dateValue}T12:00:00Z`));
}

function formatAnswer(value) {
  if (value === 'yes') {
    return 'Yes';
  }

  if (value === 'no') {
    return 'No';
  }

  return 'No answer';
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function generateClientRequestEmail(checklist) {
  const clientTasks = getClientFacingTasks(checklist.tasks);
  const groupedTasks = groupTasksByCategory(clientTasks);
  const dueDate = formatOutputDate(checklist.dueDate);
  const lines = [
    `Subject: Requested items for ${checklist.clientName} - ${checklist.workflowName}`,
    '',
    `Hello ${checklist.clientName},`,
    '',
    `I hope you are well. SAT-C LLP is preparing your ${checklist.workflowName} checklist due ${dueDate}. Please provide or review the following client-facing items when convenient.`,
    ''
  ];

  if (!groupedTasks.length) {
    lines.push('There are no client-facing requests for this checklist right now.', '');
  }

  groupedTasks.forEach(({ category, tasks }) => {
    lines.push(category);
    tasks.forEach((task) => {
      lines.push(`- ${task.title} (suggested by ${formatOutputDate(task.suggestedDate)})`);
    });
    lines.push('');
  });

  lines.push(
    'If you have questions about any item, please reply here and we will be happy to help.',
    '',
    'Thank you,',
    'SAT-C LLP'
  );

  return lines.join('\n');
}

function renderTaskList(tasks, { includeInternalDetails = false } = {}) {
  return groupTasksByCategory(tasks)
    .map(
      ({ category, tasks: categoryTasks }) => `
        <section class="print-category">
          <h2>${escapeHtml(category)}</h2>
          <ol>
            ${categoryTasks
              .map(
                (task) => `
                  <li>
                    <div class="task-title">${escapeHtml(task.title)}</div>
                    <div class="task-details">
                      <span>Suggested: ${formatOutputDate(task.suggestedDate)}</span>
                      ${
                        includeInternalDetails
                          ? `<span>Audience: ${escapeHtml(task.audienceLabel)}</span><span>Status: ${
                              task.completed ? 'Complete' : 'Open'
                            }</span>`
                          : ''
                      }
                    </div>
                    ${includeInternalDetails && task.notes ? `<p class="notes">Notes: ${escapeHtml(task.notes)}</p>` : ''}
                  </li>
                `
              )
              .join('')}
          </ol>
        </section>
      `
    )
    .join('');
}

function renderIntakeAnswers(checklist) {
  const answers = checklist.intakeAnswers ?? {};
  const questions = getWorkflowQuestions(checklist.workflowKey);

  if (!questions.length) {
    return '<p>No intake questions for this workflow.</p>';
  }

  return `
    <dl class="intake-list">
      ${questions
        .map(
          (question) => `
            <div>
              <dt>${escapeHtml(question.label)}</dt>
              <dd>${formatAnswer(answers[question.id])}</dd>
            </div>
          `
        )
        .join('')}
    </dl>
  `;
}

function buildPrintDocument({ title, intro, body }) {
  return `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          body { color: #1f2933; font-family: Arial, sans-serif; line-height: 1.5; margin: 32px; }
          h1 { margin-bottom: 4px; }
          h2 { border-bottom: 1px solid #cfd8e3; font-size: 1.05rem; margin-top: 28px; padding-bottom: 6px; }
          ol { padding-left: 24px; }
          li { margin-bottom: 14px; }
          .meta, .task-details, .notes { color: #536574; font-size: 0.92rem; }
          .task-details { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 3px; }
          .task-title { font-weight: 700; }
          .intake-list { display: grid; gap: 8px; }
          .intake-list div { border-bottom: 1px solid #e3e9ef; padding-bottom: 8px; }
          .intake-list dt { color: #536574; font-weight: 700; }
          .intake-list dd { margin: 2px 0 0; }
          @media print { body { margin: 20mm; } button { display: none; } }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>
        <p class="meta">${escapeHtml(intro)}</p>
        ${body}
      </body>
    </html>`;
}

function generateClientRequestPrintHtml(checklist) {
  const title = `Client request list - ${checklist.clientName}`;
  const intro = `${checklist.workflowName} • Due ${formatOutputDate(checklist.dueDate)} • SAT-C LLP`;
  const tasks = getClientFacingTasks(checklist.tasks);
  const body = tasks.length
    ? renderTaskList(tasks)
    : '<p>There are no client-facing requests for this checklist right now.</p>';

  return buildPrintDocument({ title, intro, body });
}

function generateInternalChecklistPrintHtml(checklist) {
  const title = `Internal checklist - ${checklist.clientName}`;
  const intro = `${checklist.workflowName} • Due ${formatOutputDate(checklist.dueDate)}`;
  const body = `
    <section>
      <h2>Intake answers</h2>
      ${renderIntakeAnswers(checklist)}
    </section>
    <section>
      <h2>Tasks</h2>
      ${renderTaskList(checklist.tasks, { includeInternalDetails: true })}
    </section>
  `;

  return buildPrintDocument({ title, intro, body });
}


// src/app.js

const STORAGE_KEY = 'workflow-task-checklists';

const form = document.querySelector('#checklist-form');
const workflowSelect = document.querySelector('#workflow');
const checklistsContainer = document.querySelector('#checklists');
const intakeQuestionnaire = document.querySelector('#intake-questionnaire');
const summary = document.querySelector('#summary');
const emptyStateTemplate = document.querySelector('#empty-state-template');
const clearAllButton = document.querySelector('#clear-all');

let checklists = loadChecklists();
let editingChecklistId = null;

function loadChecklists() {
  const savedChecklists = localStorage.getItem(STORAGE_KEY);

  if (!savedChecklists) {
    return [];
  }

  try {
    return JSON.parse(savedChecklists);
  } catch (error) {
    console.warn('Unable to load saved checklists. Starting fresh.', error);
    return [];
  }
}

function saveChecklists() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(checklists));
}

function formatDate(dateValue) {
  return new Intl.DateTimeFormat('en', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC'
  }).format(new Date(`${dateValue}T12:00:00Z`));
}

function populateWorkflowOptions() {
  workflowSelect.innerHTML = Object.entries(workflows)
    .map(([key, workflow]) => `<option value="${key}">${workflow.name}</option>`)
    .join('');
}

function renderQuestionFields(questions, answers = {}, namePrefix = 'question') {
  return questions
    .map(
      (question) => `
        <label>
          ${escapeHtml(question.label)}
          <select name="${namePrefix}:${escapeHtml(question.id)}">
            <option value="" ${!answers[question.id] ? 'selected' : ''}>No answer</option>
            <option value="yes" ${answers[question.id] === 'yes' ? 'selected' : ''}>Yes</option>
            <option value="no" ${answers[question.id] === 'no' ? 'selected' : ''}>No</option>
          </select>
        </label>
      `
    )
    .join('');
}

function renderIntakeQuestions() {
  const selectedWorkflow = workflows[workflowSelect.value];
  const questions = getWorkflowQuestions(workflowSelect.value);

  if (!questions.length) {
    intakeQuestionnaire.innerHTML = '';
    intakeQuestionnaire.hidden = true;
    return;
  }

  intakeQuestionnaire.hidden = false;
  intakeQuestionnaire.innerHTML = `
    <div class="intake-heading">
      <div>
        <p class="eyebrow">Optional intake</p>
        <h3>${escapeHtml(selectedWorkflow.name)} questions</h3>
      </div>
      <p>Answers are saved with the checklist and may add conditional tasks.</p>
    </div>
    <div class="question-grid">
      ${renderQuestionFields(questions)}
    </div>
  `;
}

function getIntakeAnswers(formData, workflowKey) {
  return getIntakeAnswersFromPrefix(formData, workflowKey, 'question');
}

function getIntakeAnswersFromPrefix(formData, workflowKey, prefix) {
  return getWorkflowQuestions(workflowKey).reduce((answers, question) => {
    answers[question.id] = formData.get(`${prefix}:${question.id}`) ?? '';
    return answers;
  }, {});
}

function formatAudience(audience) {
  if (audience === 'client') {
    return 'Client-facing';
  }

  return 'Internal';
}

function renderSummary() {
  const totalTasks = checklists.reduce((total, checklist) => total + checklist.tasks.length, 0);
  const completeTasks = checklists.reduce(
    (total, checklist) => total + checklist.tasks.filter((task) => task.completed).length,
    0
  );

  summary.textContent = checklists.length
    ? `${checklists.length} checklist${checklists.length === 1 ? '' : 's'} • ${completeTasks}/${totalTasks} tasks complete`
    : 'Nothing saved yet';
}

function renderChecklists() {
  checklistsContainer.innerHTML = '';
  renderSummary();

  if (!checklists.length) {
    checklistsContainer.append(emptyStateTemplate.content.cloneNode(true));
    return;
  }

  checklists
    .slice()
    .sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate))
    .forEach((checklist) => {
      checklistsContainer.append(createChecklistCard(checklist));
    });
}

function renderEditForm(checklist) {
  const questions = getWorkflowQuestions(checklist.workflowKey);

  return `
    <form class="edit-checklist-form" data-action="save-edit">
      <div class="edit-grid">
        <label>
          Client name
          <input name="editClientName" type="text" value="${escapeHtml(checklist.clientName)}" required />
        </label>
        <label>
          Due date
          <input name="editDueDate" type="date" value="${escapeHtml(checklist.dueDate)}" required />
        </label>
      </div>
      <div class="edit-questions">
        <div class="intake-heading">
          <div>
            <p class="eyebrow">Edit intake</p>
            <h4>${escapeHtml(checklist.workflowName)} questions</h4>
          </div>
          <p>Changing answers regenerates tasks while preserving notes and completion for matching tasks.</p>
        </div>
        <div class="question-grid">
          ${renderQuestionFields(questions, checklist.intakeAnswers ?? {}, 'editQuestion')}
        </div>
      </div>
      <div class="edit-actions">
        <button class="button button-primary" type="submit">Save changes</button>
        <button class="button button-ghost" data-action="cancel-edit" type="button">Cancel</button>
      </div>
    </form>
  `;
}

function createChecklistCard(checklist) {
  const completedTasks = checklist.tasks.filter((task) => task.completed).length;
  const intakeAnswers = checklist.intakeAnswers ?? {};
  const workflowQuestions = getWorkflowQuestions(checklist.workflowKey);
  const editForm = editingChecklistId === checklist.id ? renderEditForm(checklist) : '';
  const intakeSummary = workflowQuestions.length
    ? `
      <details class="answer-summary">
        <summary>Intake answers</summary>
        <dl>
          ${workflowQuestions
            .map(
              (question) => `
                <div>
                  <dt>${escapeHtml(question.label)}</dt>
                  <dd>${formatAnswer(intakeAnswers[question.id])}</dd>
                </div>
              `
            )
            .join('')}
        </dl>
      </details>
    `
    : '';
  const article = document.createElement('article');
  article.className = 'checklist-card';
  article.dataset.checklistId = checklist.id;

  article.innerHTML = `
    <div class="card-header">
      <div>
        <p class="eyebrow">${escapeHtml(checklist.workflowName)}</p>
        <h3>${escapeHtml(checklist.clientName)}</h3>
        <p class="description">Due ${formatDate(checklist.dueDate)} • ${completedTasks}/${checklist.tasks.length} complete</p>
      </div>
      <div class="card-actions">
        <button class="button button-ghost" data-action="edit-checklist" type="button">Edit</button>
        <button class="button button-ghost" data-action="duplicate-checklist" type="button">Duplicate</button>
        <button class="button button-ghost" data-action="copy-client-email" type="button">Copy client request email</button>
        <button class="button button-ghost" data-action="print-client-list" type="button">Print client request list</button>
        <button class="button button-ghost" data-action="print-internal-checklist" type="button">Print internal checklist</button>
        <button class="button button-danger" data-action="delete-checklist" type="button">Delete</button>
      </div>
    </div>
    ${editForm}
    ${intakeSummary}
    <div class="task-groups"></div>
  `;

  const taskGroups = article.querySelector('.task-groups');

  groupTasksByCategory(checklist.tasks).forEach(({ category, tasks }) => {
    const categorySection = document.createElement('section');
    categorySection.className = 'task-category';
    categorySection.innerHTML = `
      <div class="category-heading">
        <h4>${escapeHtml(category)}</h4>
        <span>${tasks.length} task${tasks.length === 1 ? '' : 's'}</span>
      </div>
      <ol class="task-list"></ol>
    `;

    const taskList = categorySection.querySelector('.task-list');

    tasks.forEach((task) => {
      const taskItem = document.createElement('li');
      taskItem.className = task.completed ? 'task-item is-complete' : 'task-item';
      taskItem.dataset.taskId = task.id;
      taskItem.innerHTML = `
        <div class="task-main">
          <label class="task-check">
            <input type="checkbox" ${task.completed ? 'checked' : ''} data-action="toggle-task" />
            <span>${escapeHtml(task.title)}</span>
          </label>
          <div class="task-meta">
            <span class="audience-badge audience-${escapeHtml(task.audience || 'internal')}">${escapeHtml(task.audienceLabel || formatAudience(task.audience))}</span>
            <time datetime="${task.suggestedDate}">${formatDate(task.suggestedDate)}</time>
          </div>
        </div>
        <label class="notes-label">
          Notes
          <textarea data-action="update-notes" rows="2" placeholder="Add notes, questions, or follow-up details">${escapeHtml(task.notes)}</textarea>
        </label>
      `;
      taskList.append(taskItem);
    });

    taskGroups.append(categorySection);
  });

  return article;
}

function findChecklist(checklistId) {
  return checklists.find((checklist) => checklist.id === checklistId);
}

function handleSubmit(event) {
  event.preventDefault();
  const formData = new FormData(form);
  const workflowKey = formData.get('workflow');
  const checklist = buildChecklist({
    clientName: formData.get('clientName'),
    dueDate: formData.get('dueDate'),
    workflowKey,
    answers: getIntakeAnswers(formData, workflowKey)
  });

  checklists = [checklist, ...checklists];
  editingChecklistId = null;
  saveChecklists();
  form.reset();
  renderIntakeQuestions();
  renderChecklists();
}


async function copyTextToClipboard(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.setAttribute('readonly', '');
  textarea.style.position = 'fixed';
  textarea.style.top = '-9999px';
  document.body.append(textarea);
  textarea.select();
  document.execCommand('copy');
  textarea.remove();
}

function printHtmlDocument(html) {
  const printWindow = window.open('', '_blank');

  if (!printWindow) {
    window.alert('Unable to open the print window. Please allow popups for this local app and try again.');
    return;
  }

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}

async function handleChecklistInteraction(event) {
  const action = event.target.dataset.action;

  const clickActions = [
    'delete-checklist',
    'edit-checklist',
    'cancel-edit',
    'duplicate-checklist',
    'copy-client-email',
    'print-client-list',
    'print-internal-checklist'
  ];

  if (!action || (event.type === 'click' && !clickActions.includes(action))) {
    return;
  }

  const checklistCard = event.target.closest('.checklist-card');
  const checklist = findChecklist(checklistCard.dataset.checklistId);

  if (!checklist) {
    return;
  }

  if (action === 'edit-checklist') {
    editingChecklistId = checklist.id;
    renderChecklists();
    return;
  }

  if (action === 'cancel-edit') {
    editingChecklistId = null;
    renderChecklists();
    return;
  }

  if (action === 'duplicate-checklist') {
    checklists = [duplicateChecklist(checklist), ...checklists];
    editingChecklistId = null;
    saveChecklists();
    renderChecklists();
    return;
  }

  if (action === 'save-edit') {
    event.preventDefault();
    const formData = new FormData(event.target);
    const updatedChecklist = regenerateChecklist(checklist, {
      clientName: formData.get('editClientName'),
      dueDate: formData.get('editDueDate'),
      answers: getIntakeAnswersFromPrefix(formData, checklist.workflowKey, 'editQuestion')
    });
    checklists = checklists.map((savedChecklist) =>
      savedChecklist.id === updatedChecklist.id ? updatedChecklist : savedChecklist
    );
    editingChecklistId = null;
    saveChecklists();
    renderChecklists();
    return;
  }

  if (action === 'copy-client-email') {
    try {
      await copyTextToClipboard(generateClientRequestEmail(checklist));
      event.target.textContent = 'Copied';
      window.setTimeout(() => {
        event.target.textContent = 'Copy client request email';
      }, 1600);
    } catch (error) {
      console.error('Unable to copy client request email.', error);
      window.alert('Unable to copy the email. Please try again or use a supported browser.');
    }
    return;
  }

  if (action === 'print-client-list') {
    printHtmlDocument(generateClientRequestPrintHtml(checklist));
    return;
  }

  if (action === 'print-internal-checklist') {
    printHtmlDocument(generateInternalChecklistPrintHtml(checklist));
    return;
  }

  if (action === 'delete-checklist') {
    checklists = checklists.filter((savedChecklist) => savedChecklist.id !== checklist.id);
    if (editingChecklistId === checklist.id) {
      editingChecklistId = null;
    }
  }

  if (action === 'toggle-task') {
    const taskItem = event.target.closest('.task-item');
    const task = checklist.tasks.find((savedTask) => savedTask.id === taskItem.dataset.taskId);
    task.completed = event.target.checked;
  }

  if (action === 'update-notes') {
    const taskItem = event.target.closest('.task-item');
    const task = checklist.tasks.find((savedTask) => savedTask.id === taskItem.dataset.taskId);
    task.notes = event.target.value;
    saveChecklists();
    return;
  }

  saveChecklists();
  renderChecklists();
}

function clearAllData() {
  const confirmed = window.confirm('Delete all saved checklists from this browser?');

  if (!confirmed) {
    return;
  }

  checklists = [];
  saveChecklists();
  renderChecklists();
}

populateWorkflowOptions();
renderIntakeQuestions();
renderChecklists();

form.addEventListener('submit', handleSubmit);
workflowSelect.addEventListener('change', renderIntakeQuestions);
checklistsContainer.addEventListener('submit', handleChecklistInteraction);
checklistsContainer.addEventListener('change', handleChecklistInteraction);
checklistsContainer.addEventListener('input', handleChecklistInteraction);
checklistsContainer.addEventListener('click', handleChecklistInteraction);
clearAllButton.addEventListener('click', clearAllData);

})();
